/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misc;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Abubakar Manzoor
 */
public class new_admission_form extends javax.swing.JFrame {

    /**
     * Creates new form new_admission_form
     *
     */
    //variables for holding new admission data
    String month;
    int year;

    String formno;

    String form_no;
    String Session;
    String Roll_no;
    String Date;

    String First_Name;
    String Last_Name;
    String C_B_Fromno;
    String DOB;
    String Father_Name;
    String Father_Occupation;
    String Father_CNIC;
    String Religion;
    String Contact_home;
    String Mobile;
    String Postel_Adress;
    String Permanent_Adress;
    String Tehsil;
    String District;

    String Combobox_school;
    String Combobox_college;

    String admissionfee;
    String monthlyfee;
    String cardfee;
    String badgefee;
    String booksfee;
    String uniformfee;
    String otherfee;
    String totalfee;

    String Main_Combobox;
    String Elective_subject = "None";

    public new_admission_form() {
        initComponents();
        combobox();
        TF_totalfee.setEditable(false);
    }

    void datereciever(String month1, int year1) {
        month = month1;
        year = year1;
    }

    void combobox() {

        String Query3 = "select * from classes_record;";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/misc", "root", "");
            //here sonoo is database name, root is username and password

            PreparedStatement stmt = con.prepareStatement(Query3);
            ResultSet r1 = stmt.executeQuery();

            while (r1.next()) {
                String classname = r1.getString("Class_name");
                String schoolorcollege = r1.getString("School_College");

                if ("School".equals(schoolorcollege)) {
                    Combobox_School.addItem(classname);
                }
                if ("College".equals(schoolorcollege)) {

                    Combobox_College.addItem(classname);
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    String imgPath = null;
    String path = null;

    //this is the fucntion that resize the image 
    public ImageIcon ResizeImage(String ImagePath, byte[] pic) {
        ImageIcon MyImage = null;
        if (ImagePath != null) {
            MyImage = new ImageIcon(ImagePath);
        } else {
            MyImage = new ImageIcon(pic);
        }
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lbl_Image.getWidth(), lbl_Image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);

        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gif = new javax.swing.JLabel();
        gif2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TF_fname = new javax.swing.JTextField();
        TF_lname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TF_fathername = new javax.swing.JTextField();
        TF_foccupation = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TF_religion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TF_postaladress = new javax.swing.JTextField();
        TF_permanentadress = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TF_tehsil = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TF_district = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Combobox_School = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        Combobox_College = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        TF_session = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        TF_rollno = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        lbl_Image = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        TF_fcnic = new javax.swing.JFormattedTextField();
        TF_bform1 = new javax.swing.JFormattedTextField();
        TF_contacthome = new javax.swing.JFormattedTextField();
        TF_dob = new javax.swing.JFormattedTextField();
        TF_mobile1 = new javax.swing.JFormattedTextField();
        TF_date = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        TF_admissionfee = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        TF_cardfee = new javax.swing.JTextField();
        TF_monthlyfee = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        TF_badgefee = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        TF_bookfee = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        TF_uniformfee = new javax.swing.JTextField();
        TF_otherfee = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        TF_totalfee = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        subjects = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admission Form");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                new_admission_closing(evt);
            }
        });
        getContentPane().setLayout(null);

        gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/misc/loader.gif"))); // NOI18N
        getContentPane().add(gif);
        gif.setBounds(370, 130, 140, 80);

        gif2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/misc/gif 950,550.png"))); // NOI18N
        getContentPane().add(gif2);
        gif2.setBounds(-4, 0, 770, 550);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("First Name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 110, 70, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Admission Form");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(22, 3, 910, 50);

        TF_fname.setForeground(new java.awt.Color(102, 102, 102));
        TF_fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_fnameActionPerformed(evt);
            }
        });
        getContentPane().add(TF_fname);
        TF_fname.setBounds(150, 110, 171, 20);

        TF_lname.setForeground(new java.awt.Color(153, 153, 153));
        TF_lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_lnameActionPerformed(evt);
            }
        });
        getContentPane().add(TF_lname);
        TF_lname.setBounds(460, 110, 171, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Last Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 110, 68, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Father's  Name :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 170, 93, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Father's  CNIC :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 170, 93, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Candidate B Form :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 140, 109, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("DOB :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 140, 35, 17);

        TF_fathername.setForeground(new java.awt.Color(153, 153, 153));
        TF_fathername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_fathername);
        TF_fathername.setBounds(150, 170, 171, 20);

        TF_foccupation.setForeground(new java.awt.Color(153, 153, 153));
        TF_foccupation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_foccupation);
        TF_foccupation.setBounds(150, 200, 171, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Father's Occupation : ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 200, 125, 17);

        TF_religion.setForeground(new java.awt.Color(153, 153, 153));
        TF_religion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_religion);
        TF_religion.setBounds(460, 200, 171, 20);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Religion");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(360, 200, 45, 17);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Contact (Home) : ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 230, 102, 17);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Mobile : ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(360, 230, 50, 17);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Postal Address :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 260, 91, 17);

        TF_postaladress.setForeground(new java.awt.Color(153, 153, 153));
        TF_postaladress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_postaladress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_postaladressActionPerformed(evt);
            }
        });
        getContentPane().add(TF_postaladress);
        TF_postaladress.setBounds(150, 260, 480, 20);

        TF_permanentadress.setForeground(new java.awt.Color(153, 153, 153));
        TF_permanentadress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_permanentadress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_permanentadressActionPerformed(evt);
            }
        });
        getContentPane().add(TF_permanentadress);
        TF_permanentadress.setBounds(150, 290, 480, 20);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Permanent Address :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 290, 117, 17);

        TF_tehsil.setForeground(new java.awt.Color(153, 153, 153));
        TF_tehsil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_tehsil);
        TF_tehsil.setBounds(150, 320, 171, 20);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Tehsil :");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 320, 41, 17);

        TF_district.setForeground(new java.awt.Color(153, 153, 153));
        TF_district.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_district);
        TF_district.setBounds(460, 320, 171, 20);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Academic Program :");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 347, 116, 20);

        Combobox_School.setForeground(new java.awt.Color(0, 102, 51));
        Combobox_School.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        Combobox_School.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combobox_SchoolActionPerformed(evt);
            }
        });
        getContentPane().add(Combobox_School);
        Combobox_School.setBounds(150, 350, 171, 20);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("(School)");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(50, 362, 49, 20);

        Combobox_College.setForeground(new java.awt.Color(0, 102, 51));
        Combobox_College.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        getContentPane().add(Combobox_College);
        Combobox_College.setBounds(460, 350, 171, 20);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("(College/University)");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(330, 362, 112, 20);

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(782, 260, 118, 23);

        panel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(panel1);
        panel1.setBounds(22, 53, 910, 10);

        jButton2.setText("Save & Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(830, 500, 92, 25);

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(744, 500, 80, 25);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel23.setText("District :");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(360, 320, 49, 17);

        TF_session.setForeground(new java.awt.Color(153, 153, 153));
        TF_session.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_session);
        TF_session.setBounds(75, 80, 60, 20);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setText("Session :");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(20, 80, 50, 17);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel26.setText("Roll No :");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(145, 80, 50, 17);

        TF_rollno.setForeground(new java.awt.Color(153, 153, 153));
        TF_rollno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_rollno);
        TF_rollno.setBounds(200, 80, 70, 20);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel27.setText("Date :");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(280, 80, 33, 17);

        lbl_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_Image);
        lbl_Image.setBounds(770, 90, 140, 160);

        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(660, 500, 73, 23);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("Academic Program :");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(330, 347, 116, 20);

        TF_fcnic.setForeground(new java.awt.Color(153, 153, 153));
        try {
            TF_fcnic.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TF_fcnic.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_fcnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_fcnicActionPerformed(evt);
            }
        });
        getContentPane().add(TF_fcnic);
        TF_fcnic.setBounds(460, 170, 171, 20);

        TF_bform1.setForeground(new java.awt.Color(153, 153, 153));
        try {
            TF_bform1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TF_bform1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_bform1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_bform1ActionPerformed(evt);
            }
        });
        getContentPane().add(TF_bform1);
        TF_bform1.setBounds(150, 140, 171, 20);

        TF_contacthome.setForeground(new java.awt.Color(153, 153, 153));
        try {
            TF_contacthome.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### - #######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TF_contacthome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_contacthome);
        TF_contacthome.setBounds(150, 230, 171, 20);

        TF_dob.setForeground(new java.awt.Color(153, 153, 153));
        try {
            TF_dob.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## - ## - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TF_dob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_dob);
        TF_dob.setBounds(460, 140, 171, 20);

        TF_mobile1.setForeground(new java.awt.Color(153, 153, 153));
        try {
            TF_mobile1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### - #######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TF_mobile1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_mobile1);
        TF_mobile1.setBounds(460, 230, 171, 20);

        TF_date.setForeground(new java.awt.Color(153, 153, 153));
        try {
            TF_date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## / ## / ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TF_date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_dateActionPerformed(evt);
            }
        });
        getContentPane().add(TF_date);
        TF_date.setBounds(320, 80, 78, 20);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Admission Fees :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 400, 110, 20);

        TF_admissionfee.setForeground(new java.awt.Color(153, 153, 153));
        TF_admissionfee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_admissionfee.setText("0");
        TF_admissionfee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF_admissionfeeFocusLost(evt);
            }
        });
        getContentPane().add(TF_admissionfee);
        TF_admissionfee.setBounds(150, 400, 171, 20);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setText("Fee Card :");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(20, 430, 110, 20);

        TF_cardfee.setForeground(new java.awt.Color(153, 153, 153));
        TF_cardfee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_cardfee.setText("0");
        TF_cardfee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF_cardfeeFocusLost(evt);
            }
        });
        TF_cardfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_cardfeeActionPerformed(evt);
            }
        });
        getContentPane().add(TF_cardfee);
        TF_cardfee.setBounds(150, 430, 171, 20);

        TF_monthlyfee.setForeground(new java.awt.Color(153, 153, 153));
        TF_monthlyfee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_monthlyfee.setText("0");
        TF_monthlyfee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF_monthlyfeeFocusLost(evt);
            }
        });
        getContentPane().add(TF_monthlyfee);
        TF_monthlyfee.setBounds(460, 400, 171, 20);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel24.setText("Monthly Fees :");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(360, 400, 90, 20);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel28.setText("Fee Badge :");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(360, 430, 90, 20);

        TF_badgefee.setForeground(new java.awt.Color(153, 153, 153));
        TF_badgefee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_badgefee.setText("0");
        TF_badgefee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF_badgefeeFocusLost(evt);
            }
        });
        getContentPane().add(TF_badgefee);
        TF_badgefee.setBounds(460, 430, 171, 20);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel29.setText("Fee Uniform :");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(360, 460, 90, 20);

        TF_bookfee.setForeground(new java.awt.Color(153, 153, 153));
        TF_bookfee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_bookfee.setText("0");
        TF_bookfee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF_bookfeeFocusLost(evt);
            }
        });
        getContentPane().add(TF_bookfee);
        TF_bookfee.setBounds(150, 460, 171, 20);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel30.setText("Fee Books :");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(20, 460, 110, 20);

        TF_uniformfee.setForeground(new java.awt.Color(153, 153, 153));
        TF_uniformfee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_uniformfee.setText("0");
        TF_uniformfee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF_uniformfeeFocusLost(evt);
            }
        });
        getContentPane().add(TF_uniformfee);
        TF_uniformfee.setBounds(460, 460, 171, 20);

        TF_otherfee.setForeground(new java.awt.Color(153, 153, 153));
        TF_otherfee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_otherfee.setText("0");
        TF_otherfee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF_otherfeeFocusLost(evt);
            }
        });
        getContentPane().add(TF_otherfee);
        TF_otherfee.setBounds(150, 490, 171, 20);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel31.setText("Other/Reg.Fee :");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(20, 490, 110, 20);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel32.setText("Total :");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(360, 490, 80, 20);

        TF_totalfee.setForeground(new java.awt.Color(153, 153, 153));
        TF_totalfee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_totalfee.setText("0");
        TF_totalfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_totalfeeActionPerformed(evt);
            }
        });
        getContentPane().add(TF_totalfee);
        TF_totalfee.setBounds(460, 490, 171, 20);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/misc/950, 550 Background.jpg"))); // NOI18N
        getContentPane().add(jLabel33);
        jLabel33.setBounds(0, 0, 950, 550);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Elective Subject :");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(720, 330, 100, 17);

        subjects.setForeground(new java.awt.Color(0, 102, 51));
        subjects.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Bio Science" }));
        subjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectsActionPerformed(evt);
            }
        });
        getContentPane().add(subjects);
        subjects.setBounds(730, 350, 171, 20);

        setSize(new java.awt.Dimension(957, 581));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TF_postaladressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_postaladressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_postaladressActionPerformed

    private void TF_permanentadressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_permanentadressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_permanentadressActionPerformed

    //this is the button that choose file from computer
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Imges", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);

        int result = file.showSaveDialog(null);
        //if the user click on save in JFileChoose
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();

            path = selectedFile.getAbsolutePath();
            lbl_Image.setIcon(ResizeImage(path, null));
            imgPath = path;

            path = path.replace("\\", "\\\\");

        } //if the user click on save in Jfilechooser
        else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No File Slect");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    int roll_no_register_or_not(String rollno, String classnamesearch) {
        int existed = 0;
        // existed value 0 means that student is not register

        String Query = "select * from fees_" + classnamesearch + ";";

        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/misc", "root", "");

            PreparedStatement stmt = con.prepareStatement(Query);
            ResultSet r1 = stmt.executeQuery();

            while (r1.next()) {
                String rollnogetter = r1.getString("Rollno");

                if (rollnogetter == null ? rollno == null : rollnogetter.equals(rollno)) {
                    existed = 1;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        return existed;

    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        jButton3.setEnabled(false);
        jButton2.setEnabled(false);

        gif.setVisible(true);
        gif2.setVisible(true);

        Session = TF_session.getText();
        Roll_no = TF_rollno.getText();
        Date = TF_date.getText();

        First_Name = TF_fname.getText();
        Last_Name = TF_lname.getText();
        C_B_Fromno = TF_fcnic.getText();
        DOB = TF_dob.getText();
        Father_Name = TF_fathername.getText();
        Father_CNIC = TF_fcnic.getText();
        Father_Occupation = TF_foccupation.getText();
        Religion = TF_religion.getText();
        Contact_home = TF_contacthome.getText();
        Mobile = TF_contacthome.getText();
        Postel_Adress = TF_postaladress.getText();
        Permanent_Adress = TF_permanentadress.getText();
        Tehsil = TF_tehsil.getText();
        District = TF_district.getText();

        Combobox_school = Combobox_School.getSelectedItem().toString();
        Combobox_college = Combobox_College.getSelectedItem().toString();

        admissionfee = TF_admissionfee.getText();
        monthlyfee = TF_monthlyfee.getText();
        cardfee = TF_cardfee.getText();
        badgefee = TF_badgefee.getText();
        booksfee = TF_bookfee.getText();
        uniformfee = TF_uniformfee.getText();
        otherfee = TF_otherfee.getText();
        totalfee = TF_totalfee.getText();

        check_empty_values(Combobox_school, Combobox_college);

        int value = roll_no_register_or_not(Roll_no, Main_Combobox);

        if (value == 1) {
            JOptionPane.showMessageDialog(null, "This Roll no is Already Existed Please change the Roll No");
        } else {
            data_insert_into_database();
            Set_field_to_empty();
        }

        jButton3.setEnabled(true);
        jButton2.setEnabled(true);

        gif.setVisible(false);
        gif2.setVisible(false);


    }//GEN-LAST:event_jButton3ActionPerformed

    //this function insert our data in database
    void data_insert_into_database() {

        String query_admission_table;
        String query_fees_table;
        String query_result_table;
        String query_attendance_table;

        query_admission_table = "insert into student_admission(session, roll_no, date, first_name, last_name, c_b_form_no, dob, fathers_name, fathers_cnic, fathers_occupation, religion, contact_home, mobile, postal_address,permanent_address, tehsil, district, class, elective_subject, pic_address) values('" + Session + "','" + Roll_no + "','" + Date + "','" + First_Name + "','" + Last_Name + "','" + C_B_Fromno + "','" + DOB + "','" + Father_Name + "','" + Father_CNIC + "','" + Father_Occupation + "','" + Religion + "','" + Contact_home + "','" + Mobile + "','" + Postel_Adress + "','" + Permanent_Adress + "','" + Tehsil + "','" + District + "','" + Main_Combobox + "','" + Elective_subject + "','" + path + "');";
        query_fees_table = "insert into Fees_" + Main_Combobox + "(Rollno, Name, admission, monthly, card , badge , book, uniform, other, total) values('" + Roll_no + "', '" + First_Name + "', '" + admissionfee + "', '" + monthlyfee + "', '" + cardfee + "', '" + badgefee + "', '" + booksfee + "', '" + uniformfee + "', '" + otherfee + "', '" + totalfee + "');";
        query_result_table = "insert into Result_" + Main_Combobox + "(Rollno, Name) values('" + Roll_no + "', '" + First_Name + "');";
        query_attendance_table = "insert into attendance_" + month + "_" + year + "(Class, Roll_no, Name) values('" + Main_Combobox + "', '" + Roll_no + "', '" + First_Name + "');";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/misc", "root", "");
            //here sonoo is database name, root is username and password
            java.sql.Statement stmt = con.createStatement();

            stmt.executeUpdate(query_admission_table);
            stmt.executeUpdate(query_fees_table);
            stmt.executeUpdate(query_result_table);
            stmt.executeUpdate(query_attendance_table);

            JOptionPane.showMessageDialog(null, "Data is Inserted");

            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //this is the function that checks the combo boxes 
    int combobox_checker(String cb_school, String cb_college) {
        if (!"None".equals(cb_school) && "None".equals(cb_college)) {
            Main_Combobox = cb_school;
            return 1;
        } else if (!"None".equals(cb_college) && "None".equals(cb_school)) {
            Main_Combobox = cb_college;
            return 1;
        } else if ("None".equals(cb_college) && "None".equals(cb_school)) {
            JOptionPane.showMessageDialog(null, "You have to slect one items in subjects");
            return 0;
        } else {
            JOptionPane.showMessageDialog(null, "You have to select only one items in Combo boxes");
            return 0;
        }
    }

    //this function checks is all the fileds are empty or not 
    public void check_empty_values(String cb_school, String cb_college) {
        int combobox_clear;
        combobox_clear = combobox_checker(cb_school, cb_college);

        if (combobox_clear == 0) {
            // JOptionPane.showMessageDialog(null, "u r inside the combo box function");
        } else if ("".equals(Session)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else if ("".equals(Roll_no)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else if ("".equals(Date)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else if ("".equals(First_Name)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else if ("".equals(Last_Name)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else if ("".equals(C_B_Fromno)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else if ("".equals(DOB)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else if ("".equals(Father_Name)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else if ("".equals(Father_CNIC)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else if ("".equals(Father_Occupation)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else if ("".equals(Religion)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else if ("".equals(Contact_home)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else if ("".equals(Mobile)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else if ("".equals(Postel_Adress)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else if ("".equals(Permanent_Adress)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else if ("".equals(Tehsil)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else if ("".equals(District)) {
            JOptionPane.showMessageDialog(null, "Pleaes fill every field");
        } else {

        }
    }

    //this is the function that handle buttons and combobox hidings
    void hiding() {

        gif.setVisible(false);
        gif2.setVisible(false);

        jButton3.setEnabled(true);
        jButton2.setEnabled(true);
        subjects.hide();
        jButton3.hide();
        jButton2.hide();
        jLabel19.hide();
    }

    //this function set all fields to empty
    public void Set_field_to_empty() {
        //Setting all the text field to empty
        TF_session.setText("");
        TF_rollno.setText("");
        TF_date.setText("");
        TF_dob.setText("");
        TF_bform1.setText("");
        TF_fname.setText("");
        TF_lname.setText("");
        TF_fcnic.setText("");
        TF_date.setText("");
        TF_fathername.setText("");
        TF_fcnic.setText("");
        TF_foccupation.setText("");
        TF_religion.setText("");
        TF_contacthome.setText("");
        TF_mobile1.setText("");
        TF_postaladress.setText("");
        TF_permanentadress.setText("");
        TF_tehsil.setText("");
        TF_district.setText("");
        lbl_Image.setIcon(null);

        TF_admissionfee.setText("");
        TF_monthlyfee.setText("");
        TF_cardfee.setText("");
        TF_badgefee.setText("");
        TF_bookfee.setText("");
        TF_uniformfee.setText("");
        TF_otherfee.setText("");
        TF_totalfee.setText("");

    }

    private void TF_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_lnameActionPerformed

    private void Combobox_SchoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combobox_SchoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combobox_SchoolActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Combobox_school = Combobox_School.getSelectedItem().toString();

        if ("Ninthhhhhhh".equals(Combobox_school) || "Tenthhhhh".equals(Combobox_school)) {

            Elective_subject = subjects.getSelectedItem().toString();

            subjects.show();
            jLabel19.show();
            jButton3.show();
            jButton2.show();
        } else {

            jButton3.show();
            jButton2.show();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void subjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectsActionPerformed

    private void TF_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_fnameActionPerformed
        // TF_fname.setOpaque(false);
    }//GEN-LAST:event_TF_fnameActionPerformed

    private void TF_fcnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_fcnicActionPerformed

    }//GEN-LAST:event_TF_fcnicActionPerformed

    private void TF_bform1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_bform1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_bform1ActionPerformed

    private void TF_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_dateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        jButton3.setEnabled(false);
        jButton2.setEnabled(false);

        gif.setVisible(true);
        gif2.setVisible(true);

        Session = TF_session.getText();
        Roll_no = TF_rollno.getText();
        Date = TF_date.getText();

        First_Name = TF_fname.getText();
        Last_Name = TF_lname.getText();
        C_B_Fromno = TF_fcnic.getText();
        DOB = TF_dob.getText();
        Father_Name = TF_fathername.getText();
        Father_CNIC = TF_fcnic.getText();
        Father_Occupation = TF_foccupation.getText();
        Religion = TF_religion.getText();
        Contact_home = TF_contacthome.getText();
        Mobile = TF_contacthome.getText();
        Postel_Adress = TF_postaladress.getText();
        Permanent_Adress = TF_permanentadress.getText();
        Tehsil = TF_tehsil.getText();
        District = TF_district.getText();
        Combobox_school = Combobox_School.getSelectedItem().toString();
        Combobox_college = Combobox_College.getSelectedItem().toString();
        admissionfee = TF_admissionfee.getText();
        monthlyfee = TF_monthlyfee.getText();
        cardfee = TF_cardfee.getText();
        badgefee = TF_badgefee.getText();
        booksfee = TF_bookfee.getText();
        uniformfee = TF_uniformfee.getText();
        otherfee = TF_otherfee.getText();
        totalfee = TF_totalfee.getText();

        check_empty_values(Combobox_school, Combobox_college);

        int value = roll_no_register_or_not(Roll_no, Main_Combobox);

        if (value == 1) {
            JOptionPane.showMessageDialog(null, "This Roll no is Already Existed Please change the Roll No");
        } else {

            data_insert_into_database();

            String formnogetter = "select * from student_admission where class = '" + Main_Combobox + "' AND roll_no = '" + Roll_no + "';";
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection connnn = DriverManager.getConnection("jdbc:mysql://localhost:3306/misc", "root", "");
                PreparedStatement stmt = connnn.prepareStatement(formnogetter);
                ResultSet r2 = stmt.executeQuery();

                r2.next();

                formno = r2.getString("form_no");

                connnn.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            Set_field_to_empty();

            Admission_Printing objectaddprin = new Admission_Printing();
            objectaddprin.printing(path, First_Name, Father_Name, Roll_no, formno, Main_Combobox, C_B_Fromno, DOB, Date, Father_CNIC, Father_Occupation, Religion, Contact_home, Mobile, Postel_Adress, Permanent_Adress, Tehsil, District, admissionfee, monthlyfee, cardfee, badgefee, booksfee, uniformfee, otherfee, totalfee);

        }

        jButton3.setEnabled(true);
        jButton2.setEnabled(true);

        gif.setVisible(false);
        gif2.setVisible(false);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void new_admission_closing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_new_admission_closing
        dispose();
        Main_Page.jButton2.setEnabled(true);
        Main_Page.functiongettingtotals();
    }//GEN-LAST:event_new_admission_closing

    private void TF_cardfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_cardfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_cardfeeActionPerformed

    private void TF_admissionfeeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_admissionfeeFocusLost

        String admissionfee1 = TF_admissionfee.getText();
        int admissionfee2 = Integer.parseInt(admissionfee1);

        String monthlyfee1 = TF_monthlyfee.getText();
        int monthlyfee2 = Integer.parseInt(monthlyfee1);

        String cardfee1 = TF_cardfee.getText();
        int cardfee2 = Integer.parseInt(cardfee1);

        String badgefee1 = TF_badgefee.getText();
        int badgefee2 = Integer.parseInt(badgefee1);

        String booksfee1 = TF_bookfee.getText();
        int booksfee2 = Integer.parseInt(booksfee1);

        String uniformfee1 = TF_uniformfee.getText();
        int uniformfee2 = Integer.parseInt(uniformfee1);

        String otherfee1 = TF_otherfee.getText();
        int otherfee2 = Integer.parseInt(otherfee1);

        int totalfee1 = admissionfee2 + monthlyfee2 + cardfee2 + badgefee2 + booksfee2 + uniformfee2 + otherfee2;

        String totalfee2 = totalfee1 + " Rs";
        TF_totalfee.setText(totalfee2);

    }//GEN-LAST:event_TF_admissionfeeFocusLost

    private void TF_monthlyfeeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_monthlyfeeFocusLost

        String admissionfee1 = TF_admissionfee.getText();
        int admissionfee2 = Integer.parseInt(admissionfee1);

        String monthlyfee1 = TF_monthlyfee.getText();
        int monthlyfee2 = Integer.parseInt(monthlyfee1);

        String cardfee1 = TF_cardfee.getText();
        int cardfee2 = Integer.parseInt(cardfee1);

        String badgefee1 = TF_badgefee.getText();
        int badgefee2 = Integer.parseInt(badgefee1);

        String booksfee1 = TF_bookfee.getText();
        int booksfee2 = Integer.parseInt(booksfee1);

        String uniformfee1 = TF_uniformfee.getText();
        int uniformfee2 = Integer.parseInt(uniformfee1);

        String otherfee1 = TF_otherfee.getText();
        int otherfee2 = Integer.parseInt(otherfee1);

        int totalfee1 = admissionfee2 + monthlyfee2 + cardfee2 + badgefee2 + booksfee2 + uniformfee2 + otherfee2;

        String totalfee2 = totalfee1 + "";
        TF_totalfee.setText(totalfee2);
    }//GEN-LAST:event_TF_monthlyfeeFocusLost

    private void TF_cardfeeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_cardfeeFocusLost

        String admissionfee1 = TF_admissionfee.getText();
        int admissionfee2 = Integer.parseInt(admissionfee1);

        String monthlyfee1 = TF_monthlyfee.getText();
        int monthlyfee2 = Integer.parseInt(monthlyfee1);

        String cardfee1 = TF_cardfee.getText();
        int cardfee2 = Integer.parseInt(cardfee1);

        String badgefee1 = TF_badgefee.getText();
        int badgefee2 = Integer.parseInt(badgefee1);

        String booksfee1 = TF_bookfee.getText();
        int booksfee2 = Integer.parseInt(booksfee1);

        String uniformfee1 = TF_uniformfee.getText();
        int uniformfee2 = Integer.parseInt(uniformfee1);

        String otherfee1 = TF_otherfee.getText();
        int otherfee2 = Integer.parseInt(otherfee1);

        int totalfee1 = admissionfee2 + monthlyfee2 + cardfee2 + badgefee2 + booksfee2 + uniformfee2 + otherfee2;

        String totalfee2 = totalfee1 + "";
        TF_totalfee.setText(totalfee2);        // TODO add your handling code here:
    }//GEN-LAST:event_TF_cardfeeFocusLost

    private void TF_badgefeeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_badgefeeFocusLost

        String admissionfee1 = TF_admissionfee.getText();
        int admissionfee2 = Integer.parseInt(admissionfee1);

        String monthlyfee1 = TF_monthlyfee.getText();
        int monthlyfee2 = Integer.parseInt(monthlyfee1);

        String cardfee1 = TF_cardfee.getText();
        int cardfee2 = Integer.parseInt(cardfee1);

        String badgefee1 = TF_badgefee.getText();
        int badgefee2 = Integer.parseInt(badgefee1);

        String booksfee1 = TF_bookfee.getText();
        int booksfee2 = Integer.parseInt(booksfee1);

        String uniformfee1 = TF_uniformfee.getText();
        int uniformfee2 = Integer.parseInt(uniformfee1);

        String otherfee1 = TF_otherfee.getText();
        int otherfee2 = Integer.parseInt(otherfee1);

        int totalfee1 = admissionfee2 + monthlyfee2 + cardfee2 + badgefee2 + booksfee2 + uniformfee2 + otherfee2;

        String totalfee2 = totalfee1 + "";
        TF_totalfee.setText(totalfee2);        // TODO add your handling code here:
    }//GEN-LAST:event_TF_badgefeeFocusLost

    private void TF_bookfeeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_bookfeeFocusLost

        String admissionfee1 = TF_admissionfee.getText();
        int admissionfee2 = Integer.parseInt(admissionfee1);

        String monthlyfee1 = TF_monthlyfee.getText();
        int monthlyfee2 = Integer.parseInt(monthlyfee1);

        String cardfee1 = TF_cardfee.getText();
        int cardfee2 = Integer.parseInt(cardfee1);

        String badgefee1 = TF_badgefee.getText();
        int badgefee2 = Integer.parseInt(badgefee1);

        String booksfee1 = TF_bookfee.getText();
        int booksfee2 = Integer.parseInt(booksfee1);

        String uniformfee1 = TF_uniformfee.getText();
        int uniformfee2 = Integer.parseInt(uniformfee1);

        String otherfee1 = TF_otherfee.getText();
        int otherfee2 = Integer.parseInt(otherfee1);

        int totalfee1 = admissionfee2 + monthlyfee2 + cardfee2 + badgefee2 + booksfee2 + uniformfee2 + otherfee2;

        String totalfee2 = totalfee1 + "";
        TF_totalfee.setText(totalfee2);        // TODO add your handling code here:
    }//GEN-LAST:event_TF_bookfeeFocusLost

    private void TF_uniformfeeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_uniformfeeFocusLost

        String admissionfee1 = TF_admissionfee.getText();
        int admissionfee2 = Integer.parseInt(admissionfee1);

        String monthlyfee1 = TF_monthlyfee.getText();
        int monthlyfee2 = Integer.parseInt(monthlyfee1);

        String cardfee1 = TF_cardfee.getText();
        int cardfee2 = Integer.parseInt(cardfee1);

        String badgefee1 = TF_badgefee.getText();
        int badgefee2 = Integer.parseInt(badgefee1);

        String booksfee1 = TF_bookfee.getText();
        int booksfee2 = Integer.parseInt(booksfee1);

        String uniformfee1 = TF_uniformfee.getText();
        int uniformfee2 = Integer.parseInt(uniformfee1);

        String otherfee1 = TF_otherfee.getText();
        int otherfee2 = Integer.parseInt(otherfee1);

        int totalfee1 = admissionfee2 + monthlyfee2 + cardfee2 + badgefee2 + booksfee2 + uniformfee2 + otherfee2;

        String totalfee2 = totalfee1 + "";
        TF_totalfee.setText(totalfee2);        // TODO add your handling code here:
    }//GEN-LAST:event_TF_uniformfeeFocusLost

    private void TF_otherfeeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_otherfeeFocusLost

        String admissionfee1 = TF_admissionfee.getText();
        int admissionfee2 = Integer.parseInt(admissionfee1);

        String monthlyfee1 = TF_monthlyfee.getText();
        int monthlyfee2 = Integer.parseInt(monthlyfee1);

        String cardfee1 = TF_cardfee.getText();
        int cardfee2 = Integer.parseInt(cardfee1);

        String badgefee1 = TF_badgefee.getText();
        int badgefee2 = Integer.parseInt(badgefee1);

        String booksfee1 = TF_bookfee.getText();
        int booksfee2 = Integer.parseInt(booksfee1);

        String uniformfee1 = TF_uniformfee.getText();
        int uniformfee2 = Integer.parseInt(uniformfee1);

        String otherfee1 = TF_otherfee.getText();
        int otherfee2 = Integer.parseInt(otherfee1);

        int totalfee1 = admissionfee2 + monthlyfee2 + cardfee2 + badgefee2 + booksfee2 + uniformfee2 + otherfee2;

        String totalfee2 = totalfee1 + "";
        TF_totalfee.setText(totalfee2);        // TODO add your handling code here:
    }//GEN-LAST:event_TF_otherfeeFocusLost

    private void TF_totalfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_totalfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_totalfeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_admission_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_admission_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_admission_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_admission_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_admission_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combobox_College;
    private javax.swing.JComboBox<String> Combobox_School;
    private javax.swing.JTextField TF_admissionfee;
    private javax.swing.JTextField TF_badgefee;
    private javax.swing.JFormattedTextField TF_bform1;
    private javax.swing.JTextField TF_bookfee;
    private javax.swing.JTextField TF_cardfee;
    private javax.swing.JFormattedTextField TF_contacthome;
    private javax.swing.JFormattedTextField TF_date;
    private javax.swing.JTextField TF_district;
    private javax.swing.JFormattedTextField TF_dob;
    private javax.swing.JTextField TF_fathername;
    private javax.swing.JFormattedTextField TF_fcnic;
    private javax.swing.JTextField TF_fname;
    private javax.swing.JTextField TF_foccupation;
    private javax.swing.JTextField TF_lname;
    private javax.swing.JFormattedTextField TF_mobile1;
    private javax.swing.JTextField TF_monthlyfee;
    private javax.swing.JTextField TF_otherfee;
    private javax.swing.JTextField TF_permanentadress;
    private javax.swing.JTextField TF_postaladress;
    private javax.swing.JTextField TF_religion;
    private javax.swing.JTextField TF_rollno;
    private javax.swing.JTextField TF_session;
    private javax.swing.JTextField TF_tehsil;
    private javax.swing.JTextField TF_totalfee;
    private javax.swing.JTextField TF_uniformfee;
    private javax.swing.JLabel gif;
    private javax.swing.JLabel gif2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_Image;
    private java.awt.Panel panel1;
    private javax.swing.JComboBox<String> subjects;
    // End of variables declaration//GEN-END:variables
}
