/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misc;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import static misc.Main_Page.functiongettingtotals;

/**
 *
 * @author Abubakar Manzoor
 */
public class new_Teacher_form extends javax.swing.JFrame {

    /**
     * Creates new form Student_form
     */
    public new_Teacher_form() {
        initComponents();
    }

    void timereciever2(String month1, int year1) {
        month = month1;
        year = year1;
    }
    String month;
    int year;

    String stafftype = "teacher";
    String Salary;
    String formno;
    String teacherid;
    String firstname;
    String lastname;
    String teacherCNIC;
    String dob;
    String fathername;
    String fatherCNIC;
    String religion;
    String district;
    String contacthome;
    String contactmobile;
    String postaladress;
    String permanentadress;

    String degree1 = "none";
    String year1 = "none";
    String grade1 = "none";
    String university1 = "none";
    String degree2 = "none";
    String year2 = "none";
    String grade2 = "none";
    String university2 = "none";
    String degree3 = "none";
    String year3 = "none";
    String grade3 = "none";
    String university3 = "none";
    String degree4 = "none";
    String year4 = "none";
    String grade4 = "none";
    String university4 = "none";
    String degree5 = "none";
    String year5 = "none";
    String grade5 = "none";
    String university5 = "none";
    String pic_adress;

    String imgPath = null;
    String path = null;

    public ImageIcon ResizeImage(String ImagePath, byte[] pic) {
        ImageIcon MyImage = null;
        if (ImagePath != null) {
            MyImage = new ImageIcon(ImagePath);
        } else {
            MyImage = new ImageIcon(pic);
        }
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lbl_Image.getWidth(), lbl_Image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TF_firstname = new javax.swing.JTextField();
        TF_lastname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TF_fathername = new javax.swing.JTextField();
        TF_religion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TF_postaladress = new javax.swing.JTextField();
        TF_permanentadress = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TF_district = new javax.swing.JTextField();
        TF_degree1 = new javax.swing.JTextField();
        TF_yearpassing1 = new javax.swing.JTextField();
        TF_grade1 = new javax.swing.JTextField();
        TF_University1 = new javax.swing.JTextField();
        Browse_Button = new javax.swing.JButton();
        Save_Button = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        TF_University2 = new javax.swing.JTextField();
        TF_grade2 = new javax.swing.JTextField();
        TF_yearpassing2 = new javax.swing.JTextField();
        TF_degree2 = new javax.swing.JTextField();
        TF_University3 = new javax.swing.JTextField();
        TF_grade3 = new javax.swing.JTextField();
        TF_yearpassing3 = new javax.swing.JTextField();
        TF_degree3 = new javax.swing.JTextField();
        TF_University4 = new javax.swing.JTextField();
        TF_grade4 = new javax.swing.JTextField();
        TF_yearpassing4 = new javax.swing.JTextField();
        TF_degree4 = new javax.swing.JTextField();
        TF_University5 = new javax.swing.JTextField();
        TF_grade5 = new javax.swing.JTextField();
        TF_yearpassing5 = new javax.swing.JTextField();
        TF_degree5 = new javax.swing.JTextField();
        lbl_Image = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        TF_contact = new javax.swing.JFormattedTextField();
        TF_teacherCNIC = new javax.swing.JFormattedTextField();
        TF_fatherCNIC = new javax.swing.JFormattedTextField();
        TF_dob = new javax.swing.JFormattedTextField();
        TF_mobile = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        TF_Salary = new javax.swing.JFormattedTextField();
        TF_teacherid = new javax.swing.JFormattedTextField();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Teacher");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                newteachingformclosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("First Name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 105, 70, 17);

        TF_firstname.setForeground(new java.awt.Color(102, 102, 102));
        TF_firstname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_firstname);
        TF_firstname.setBounds(150, 105, 171, 20);

        TF_lastname.setForeground(new java.awt.Color(102, 102, 102));
        TF_lastname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_lastname);
        TF_lastname.setBounds(460, 105, 171, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Last Name :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 105, 68, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Father's  Name :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 165, 93, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Father's  CNIC :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 165, 93, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Teacher's CNIC :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 135, 99, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("DOB :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(360, 135, 35, 17);

        TF_fathername.setForeground(new java.awt.Color(102, 102, 102));
        TF_fathername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_fathername);
        TF_fathername.setBounds(150, 165, 171, 20);

        TF_religion.setForeground(new java.awt.Color(102, 102, 102));
        TF_religion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_religion);
        TF_religion.setBounds(150, 195, 171, 20);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Religion");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 195, 45, 17);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Contact (Home) : ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 225, 102, 17);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Mobile : ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(360, 225, 49, 17);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Postal Address :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 255, 91, 17);

        TF_postaladress.setForeground(new java.awt.Color(102, 102, 102));
        TF_postaladress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_postaladress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_postaladressActionPerformed(evt);
            }
        });
        getContentPane().add(TF_postaladress);
        TF_postaladress.setBounds(150, 255, 480, 20);

        TF_permanentadress.setForeground(new java.awt.Color(102, 102, 102));
        TF_permanentadress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_permanentadress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_permanentadressActionPerformed(evt);
            }
        });
        getContentPane().add(TF_permanentadress);
        TF_permanentadress.setBounds(150, 285, 480, 20);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Permanent Address :");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 285, 117, 17);

        TF_district.setForeground(new java.awt.Color(102, 102, 102));
        TF_district.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_district);
        TF_district.setBounds(460, 195, 171, 20);

        TF_degree1.setForeground(new java.awt.Color(102, 102, 102));
        TF_degree1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_degree1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_degree1ActionPerformed(evt);
            }
        });
        getContentPane().add(TF_degree1);
        TF_degree1.setBounds(20, 400, 180, 20);

        TF_yearpassing1.setForeground(new java.awt.Color(102, 102, 102));
        TF_yearpassing1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_yearpassing1);
        TF_yearpassing1.setBounds(250, 400, 80, 20);

        TF_grade1.setForeground(new java.awt.Color(102, 102, 102));
        TF_grade1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_grade1);
        TF_grade1.setBounds(370, 400, 80, 20);

        TF_University1.setForeground(new java.awt.Color(102, 102, 102));
        TF_University1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_University1);
        TF_University1.setBounds(480, 400, 180, 20);

        Browse_Button.setText("Browse");
        Browse_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Browse_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Browse_Button);
        Browse_Button.setBounds(781, 275, 118, 23);

        Save_Button.setText("Save");
        Save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Save_Button);
        Save_Button.setBounds(800, 500, 80, 23);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setText("District :");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(360, 195, 49, 17);

        panel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(panel1);
        panel1.setBounds(20, 55, 905, 10);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Qualification");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 340, 650, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Teacher Admission Form");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 10, 900, 40);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Degree/Program");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(20, 370, 180, 17);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Year Passing");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(250, 370, 80, 17);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Grade / %age");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(370, 370, 80, 17);

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Board/University");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(480, 370, 180, 17);

        TF_University2.setForeground(new java.awt.Color(102, 102, 102));
        TF_University2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_University2);
        TF_University2.setBounds(480, 430, 180, 20);

        TF_grade2.setForeground(new java.awt.Color(102, 102, 102));
        TF_grade2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_grade2);
        TF_grade2.setBounds(370, 430, 80, 20);

        TF_yearpassing2.setForeground(new java.awt.Color(102, 102, 102));
        TF_yearpassing2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_yearpassing2);
        TF_yearpassing2.setBounds(250, 430, 80, 20);

        TF_degree2.setForeground(new java.awt.Color(102, 102, 102));
        TF_degree2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_degree2);
        TF_degree2.setBounds(20, 430, 180, 20);

        TF_University3.setForeground(new java.awt.Color(102, 102, 102));
        TF_University3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_University3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_University3ActionPerformed(evt);
            }
        });
        getContentPane().add(TF_University3);
        TF_University3.setBounds(480, 460, 180, 20);

        TF_grade3.setForeground(new java.awt.Color(102, 102, 102));
        TF_grade3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_grade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_grade3ActionPerformed(evt);
            }
        });
        getContentPane().add(TF_grade3);
        TF_grade3.setBounds(370, 460, 80, 20);

        TF_yearpassing3.setForeground(new java.awt.Color(102, 102, 102));
        TF_yearpassing3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_yearpassing3);
        TF_yearpassing3.setBounds(250, 460, 80, 20);

        TF_degree3.setForeground(new java.awt.Color(102, 102, 102));
        TF_degree3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_degree3);
        TF_degree3.setBounds(20, 460, 180, 20);

        TF_University4.setForeground(new java.awt.Color(102, 102, 102));
        TF_University4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_University4);
        TF_University4.setBounds(480, 490, 180, 20);

        TF_grade4.setForeground(new java.awt.Color(102, 102, 102));
        TF_grade4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_grade4);
        TF_grade4.setBounds(370, 490, 80, 20);

        TF_yearpassing4.setForeground(new java.awt.Color(102, 102, 102));
        TF_yearpassing4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_yearpassing4);
        TF_yearpassing4.setBounds(250, 490, 80, 20);

        TF_degree4.setForeground(new java.awt.Color(102, 102, 102));
        TF_degree4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_degree4);
        TF_degree4.setBounds(20, 490, 180, 20);

        TF_University5.setForeground(new java.awt.Color(102, 102, 102));
        TF_University5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_University5);
        TF_University5.setBounds(480, 520, 180, 20);

        TF_grade5.setForeground(new java.awt.Color(102, 102, 102));
        TF_grade5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_grade5);
        TF_grade5.setBounds(370, 520, 80, 20);

        TF_yearpassing5.setForeground(new java.awt.Color(102, 102, 102));
        TF_yearpassing5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_yearpassing5);
        TF_yearpassing5.setBounds(250, 520, 80, 20);

        TF_degree5.setForeground(new java.awt.Color(102, 102, 102));
        TF_degree5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_degree5);
        TF_degree5.setBounds(20, 520, 180, 20);

        lbl_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_Image);
        lbl_Image.setBounds(770, 105, 140, 160);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel29.setText("Teacher ID:");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(20, 75, 70, 17);

        TF_contact.setForeground(new java.awt.Color(102, 102, 102));
        try {
            TF_contact.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TF_contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_contact);
        TF_contact.setBounds(150, 225, 171, 20);

        TF_teacherCNIC.setForeground(new java.awt.Color(102, 102, 102));
        try {
            TF_teacherCNIC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TF_teacherCNIC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_teacherCNIC);
        TF_teacherCNIC.setBounds(150, 135, 171, 20);

        TF_fatherCNIC.setForeground(new java.awt.Color(102, 102, 102));
        try {
            TF_fatherCNIC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TF_fatherCNIC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_fatherCNIC);
        TF_fatherCNIC.setBounds(460, 165, 171, 20);

        TF_dob.setForeground(new java.awt.Color(102, 102, 102));
        try {
            TF_dob.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## - ## - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TF_dob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_dob);
        TF_dob.setBounds(460, 135, 171, 20);

        TF_mobile.setForeground(new java.awt.Color(102, 102, 102));
        try {
            TF_mobile.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TF_mobile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_mobile);
        TF_mobile.setBounds(460, 225, 171, 20);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("Salary :");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(20, 315, 42, 17);

        TF_Salary.setForeground(new java.awt.Color(102, 102, 102));
        TF_Salary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_Salary);
        TF_Salary.setBounds(150, 315, 171, 20);

        TF_teacherid.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        getContentPane().add(TF_teacherid);
        TF_teacherid.setBounds(120, 70, 70, 20);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/misc/950, 550 Background.jpg"))); // NOI18N
        getContentPane().add(jLabel33);
        jLabel33.setBounds(0, 0, 950, 550);

        setSize(new java.awt.Dimension(956, 579));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TF_postaladressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_postaladressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_postaladressActionPerformed

    private void TF_permanentadressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_permanentadressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_permanentadressActionPerformed

    private void TF_grade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_grade3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_grade3ActionPerformed

    //Function To Add Image In The Image_Label
    private void Browse_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Browse_ButtonActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Imges", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        //if the user click on save in JFileChoose
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            path = selectedFile.getAbsolutePath();
            lbl_Image.setIcon(ResizeImage(path, null));
            imgPath = path;
            path = path.replace("\\", "\\\\");

        } //if the user click on save in Jfilechooser
        else if (result == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "No File Selected");
        }
    }//GEN-LAST:event_Browse_ButtonActionPerformed

    private void TF_degree1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_degree1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_degree1ActionPerformed

    int teacher_found_or_not(String stafftype1, String staffRollno) {
        int found = 0;

        String Query = "select * from teacher_admission where Staff_type = '" + stafftype1 + "';";

        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/misc", "root", "");

            PreparedStatement stmt = con.prepareStatement(Query);
            ResultSet r1 = stmt.executeQuery();

            while (r1.next()) {
                String rollnogetter = r1.getString("teacher_id");

                if (rollnogetter == null ? staffRollno == null : rollnogetter.equals(staffRollno)) {
                    found = 1;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        return found;
    }


    private void Save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_ButtonActionPerformed

        teacherid = TF_teacherid.getText();

        int foundornot = teacher_found_or_not("teacher", teacherid);

        if (foundornot == 0) {
            firstname = TF_firstname.getText();
            lastname = TF_lastname.getText();
            teacherCNIC = TF_teacherCNIC.getText();
            dob = TF_dob.getText();
            fathername = TF_fathername.getText();
            fatherCNIC = TF_fatherCNIC.getText();
            religion = TF_religion.getText();
            district = TF_district.getText();
            contacthome = TF_contact.getText();
            contactmobile = TF_mobile.getText();
            postaladress = TF_postaladress.getText();
            permanentadress = TF_permanentadress.getText();
            Salary = TF_Salary.getText();

            if (!"".equals(TF_degree1.getText())) {
                degree1 = TF_degree1.getText();
            }
            if (!"".equals(TF_yearpassing1.getText())) {
                year1 = TF_yearpassing1.getText();
            }
            if (!"".equals(TF_grade1.getText())) {
                grade1 = TF_grade1.getText();
            }
            if (!"".equals(TF_University1.getText())) {
                university1 = TF_University1.getText();;
            }

            if (!"".equals(TF_degree2.getText())) {
                degree2 = TF_degree2.getText();
            }
            if (!"".equals(TF_yearpassing2.getText())) {
                year2 = TF_yearpassing2.getText();
            }
            if (!"".equals(TF_grade2.getText())) {
                grade2 = TF_grade2.getText();
            }
            if (!"".equals(TF_University2.getText())) {
                university2 = TF_University2.getText();;
            }

            if (!"".equals(TF_degree3.getText())) {
                degree3 = TF_degree3.getText();
            }
            if (!"".equals(TF_yearpassing3.getText())) {
                year3 = TF_yearpassing3.getText();
            }
            if (!"".equals(TF_grade3.getText())) {
                grade3 = TF_grade3.getText();
            }
            if (!"".equals(TF_University3.getText())) {
                university3 = TF_University3.getText();;
            }

            if (!"".equals(TF_degree4.getText())) {
                degree4 = TF_degree4.getText();
            }
            if (!"".equals(TF_yearpassing4.getText())) {
                year4 = TF_yearpassing4.getText();
            }
            if (!"".equals(TF_grade4.getText())) {
                grade4 = TF_grade4.getText();
            }
            if (!"".equals(TF_University4.getText())) {
                university4 = TF_University4.getText();;
            }

            if (!"".equals(TF_degree5.getText())) {
                degree5 = TF_degree5.getText();
            }
            if (!"".equals(TF_yearpassing5.getText())) {
                year5 = TF_yearpassing5.getText();
            }
            if (!"".equals(TF_grade5.getText())) {
                grade5 = TF_grade5.getText();
            }
            if (!"".equals(TF_University5.getText())) {
                university5 = TF_University5.getText();;
            }

            pic_adress = path;

            int value1 = check_empty_values();

            if (value1 == 1) {
                data_insert_into_database();
                Set_field_to_empty();
                JOptionPane.showMessageDialog(null, "New Teacher Admitted Successfully");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Teacher ID Already existed in the System");
        }

    }//GEN-LAST:event_Save_ButtonActionPerformed

    //this function insert data into databsae
    void data_insert_into_database() {

        String teacher_table = "teacher_attendance_" + month + "_" + year;

        String teacher_admission_query;
        String teacher_salary_query;
        String teacher_attendance_query;

        teacher_admission_query = "insert into teacher_admission(Staff_type, teacher_id, first_name, last_name, teacher_cnic, dob, fathers_name, fathers_cnic, religion, District, contact_home, mobile, postal_address,permanent_address, degree1, year_passing1, grade1, uni1, degree2, year_passing2, grade2, uni2, degree3, year_passing3, grade3, uni3, degree4, year_passing4, grade4, uni4, degree5, year_passing5, grade5, uni5, picadress) values('" + stafftype + "', '" + teacherid + "','" + firstname + "','" + lastname + "','" + teacherCNIC + "','" + dob + "','" + fathername + "','" + fatherCNIC + "','" + religion + "','" + district + "','" + contacthome + "','" + contactmobile + "','" + postaladress + "','" + permanentadress + "','" + degree1 + "','" + year1 + "','" + grade1 + "','" + university1 + "','" + degree2 + "','" + year2 + "','" + grade2 + "','" + university2 + "','" + degree3 + "','" + year3 + "','" + grade3 + "','" + university3 + "','" + degree4 + "','" + year4 + "','" + grade4 + "','" + university4 + "','" + degree5 + "','" + year5 + "','" + grade5 + "','" + university5 + "','" + pic_adress + "');";
        teacher_salary_query = "insert into salary(stafftype, staffid, staffname, totalsalary) values( 'teacher' , " + teacherid + " , '" + firstname + "' , " + Salary + ");";
        teacher_attendance_query = "insert into " + teacher_table + "(Staff_type, Staff_id, Name) values ( 'teacher', '" + teacherid + "','" + firstname + "');";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/misc", "root", "");
            //here sonoo is database name, root is username and password
            java.sql.Statement stmt = con.createStatement();

            stmt.executeUpdate(teacher_admission_query);
            stmt.executeUpdate(teacher_salary_query);
            stmt.executeUpdate(teacher_attendance_query);

            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //this function checks is all the fileds are empty or not 
    int check_empty_values() {

        int value = 0;
        if ("".equals(formno)) {
            JOptionPane.showMessageDialog(null, "Form_no Field Empty");
        } else if ("".equals(teacherid)) {
            JOptionPane.showMessageDialog(null, "Teacher_Id Field Empty");
        } else if ("".equals(firstname)) {
            JOptionPane.showMessageDialog(null, "First_Name Field Empty");
        } else if ("".equals(lastname)) {
            JOptionPane.showMessageDialog(null, "Last_Name Field Empty");
        } else if ("".equals(teacherCNIC)) {
            JOptionPane.showMessageDialog(null, "Teacher_CNIC Field Empty");
        } else if ("".equals(dob)) {
            JOptionPane.showMessageDialog(null, "Date_Of_Birth Field Empty");
        } else if ("".equals(fathername)) {
            JOptionPane.showMessageDialog(null, "Father_Name Field Empty");
        } else if ("".equals(fatherCNIC)) {
            JOptionPane.showMessageDialog(null, "Father_CNIC Field Empty");
        } else if ("".equals(religion)) {
            JOptionPane.showMessageDialog(null, "Religion Field Empty");
        } else if ("".equals(district)) {
            JOptionPane.showMessageDialog(null, "District Field Empty");
        } else if ("".equals(contacthome)) {
            JOptionPane.showMessageDialog(null, "Contact_Home Field Empty");
        } else if ("".equals(contactmobile)) {
            JOptionPane.showMessageDialog(null, "Contact_Mobile Field Empty");
        } else if ("".equals(postaladress)) {
            JOptionPane.showMessageDialog(null, "Postal_Address Field Empty");
        } else if ("".equals(permanentadress)) {
            JOptionPane.showMessageDialog(null, "Permanent_Address Field Empty");
        } else {
            value = 1;
        }

        return value;
    }

    //this function set all fields to empty
    public void Set_field_to_empty() {
        TF_teacherid.setText("");
        TF_firstname.setText("");
        TF_lastname.setText("");
        TF_teacherCNIC.setText("");
        TF_dob.setText("");
        TF_fathername.setText("");
        TF_fatherCNIC.setText("");
        TF_religion.setText("");
        TF_district.setText("");
        TF_contact.setText("");
        TF_mobile.setText("");
        TF_postaladress.setText("");
        TF_permanentadress.setText("");
        TF_degree1.setText("");
        TF_yearpassing1.setText("");
        TF_grade1.setText("");
        TF_University1.setText("");
        TF_degree2.setText("");
        TF_yearpassing2.setText("");
        TF_grade2.setText("");
        TF_University2.setText("");
        TF_degree3.setText("");
        TF_yearpassing3.setText("");
        TF_grade3.setText("");
        TF_University3.setText("");
        TF_degree4.setText("");
        TF_yearpassing4.setText("");
        TF_grade4.setText("");
        TF_University4.setText("");
        TF_degree5.setText("");
        TF_yearpassing5.setText("");
        TF_grade5.setText("");
        TF_University5.setText("");
        lbl_Image.setIcon(null);

    }

    private void TF_University3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_University3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_University3ActionPerformed

    private void newteachingformclosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_newteachingformclosing

        dispose();
        Main_Page.jButton6.setEnabled(true);
        Main_Page.functiongettingtotals();

    }//GEN-LAST:event_newteachingformclosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_Teacher_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_Teacher_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_Teacher_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_Teacher_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_Teacher_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Browse_Button;
    private javax.swing.JButton Save_Button;
    private javax.swing.JFormattedTextField TF_Salary;
    private javax.swing.JTextField TF_University1;
    private javax.swing.JTextField TF_University2;
    private javax.swing.JTextField TF_University3;
    private javax.swing.JTextField TF_University4;
    private javax.swing.JTextField TF_University5;
    private javax.swing.JFormattedTextField TF_contact;
    private javax.swing.JTextField TF_degree1;
    private javax.swing.JTextField TF_degree2;
    private javax.swing.JTextField TF_degree3;
    private javax.swing.JTextField TF_degree4;
    private javax.swing.JTextField TF_degree5;
    private javax.swing.JTextField TF_district;
    private javax.swing.JFormattedTextField TF_dob;
    private javax.swing.JFormattedTextField TF_fatherCNIC;
    private javax.swing.JTextField TF_fathername;
    private javax.swing.JTextField TF_firstname;
    private javax.swing.JTextField TF_grade1;
    private javax.swing.JTextField TF_grade2;
    private javax.swing.JTextField TF_grade3;
    private javax.swing.JTextField TF_grade4;
    private javax.swing.JTextField TF_grade5;
    private javax.swing.JTextField TF_lastname;
    private javax.swing.JFormattedTextField TF_mobile;
    private javax.swing.JTextField TF_permanentadress;
    private javax.swing.JTextField TF_postaladress;
    private javax.swing.JTextField TF_religion;
    private javax.swing.JFormattedTextField TF_teacherCNIC;
    private javax.swing.JFormattedTextField TF_teacherid;
    private javax.swing.JTextField TF_yearpassing1;
    private javax.swing.JTextField TF_yearpassing2;
    private javax.swing.JTextField TF_yearpassing3;
    private javax.swing.JTextField TF_yearpassing4;
    private javax.swing.JTextField TF_yearpassing5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_Image;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
