/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misc;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Abubakar Manzoor
 */
public class Non_teaching_form extends javax.swing.JFrame {

    /**
     * Creates new form Student_form
     */
    public Non_teaching_form() {
        initComponents();
    }

    void timereciever3(String month3, int year3) {
        month = month3;
        year = year3;
    }

    String month;
    int year;

    String Staff_type = "non_teaching";
    String formno;
    String staffid;
    String firstname;
    String lastname;
    String CNIC;
    String DOB;
    String fathername;
    String fatherCNIC;
    String religion;
    String district;
    String contacthome;
    String mobile;
    String postaladress;
    String permanentadress;
    String degree1 = "None";
    String degree2 = "None";
    String year1 = "None";
    String year2 = "None";
    String grade1 = "None";
    String grade2 = "None";
    String university1 = "None";
    String university2 = "None";
    String description;
    String pic_adress;

    public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    void put_values_to_textfields() {

        TF_formno.setText(formno);
        TF_firstname.setText(firstname);
        TF_lastname.setText(lastname);
        TF_CNIC.setText(CNIC);
        TF_dob.setText(DOB);
        TF_fathername.setText(fathername);
        TF_fatherCNIC.setText(fatherCNIC);
        TF_religion.setText(religion);
        TF_district.setText(district);
        TF_contacthome.setText(contacthome);
        TF_mobile.setText(mobile);
        TF_postaladress.setText(postaladress);
        TF_permanentadress.setText(permanentadress);
        TF_degree1.setText(degree1);
        TF_year1.setText(year1);
        TF_grade1.setText(grade1);
        TF_university1.setText(university1);
        TF_degree2.setText(degree2);
        TF_year2.setText(year2);
        TF_grade2.setText(grade2);
        TF_university2.setText(university2);
        TF_description.setText(description);

        lbl_Image.setIcon(ResizeImage(pic_adress, null));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TF_staffid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NonTeaching_Search_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TF_firstname = new javax.swing.JTextField();
        TF_lastname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TF_CNIC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TF_dob = new javax.swing.JFormattedTextField();
        TF_fathername = new javax.swing.JTextField();
        TF_fatherCNIC = new javax.swing.JTextField();
        TF_religion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TF_contacthome = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TF_mobile = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TF_postaladress = new javax.swing.JTextField();
        TF_description = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TF_district = new javax.swing.JTextField();
        NonTeaching_Update_Button = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        TF_formno = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        Add_New_Staff_Button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TF_permanentadress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        TF_degree1 = new javax.swing.JTextField();
        TF_year1 = new javax.swing.JTextField();
        TF_grade1 = new javax.swing.JTextField();
        TF_university1 = new javax.swing.JTextField();
        TF_degree2 = new javax.swing.JTextField();
        TF_year2 = new javax.swing.JTextField();
        TF_grade2 = new javax.swing.JTextField();
        TF_university2 = new javax.swing.JTextField();
        lbl_Image = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Teacher Information");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closingnonteacherform(evt);
            }
        });
        getContentPane().setLayout(null);

        TF_staffid.setForeground(new java.awt.Color(102, 102, 102));
        TF_staffid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_staffid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_staffidActionPerformed(evt);
            }
        });
        getContentPane().add(TF_staffid);
        TF_staffid.setBounds(75, 69, 60, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel5.setText("Staff ID:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 69, 60, 20);

        NonTeaching_Search_Button.setText("Search");
        NonTeaching_Search_Button.setToolTipText("");
        NonTeaching_Search_Button.setBorder(null);
        NonTeaching_Search_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NonTeaching_Search_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NonTeaching_Search_Button);
        NonTeaching_Search_Button.setBounds(155, 69, 70, 22);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("First Name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 150, 70, 17);

        TF_firstname.setForeground(new java.awt.Color(102, 102, 102));
        TF_firstname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_firstname.setToolTipText("");
        TF_firstname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(TF_firstname);
        TF_firstname.setBounds(150, 150, 171, 20);

        TF_lastname.setForeground(new java.awt.Color(102, 102, 102));
        TF_lastname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_lastname);
        TF_lastname.setBounds(460, 150, 171, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Last Name :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 150, 68, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Father's  Name :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 210, 93, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Father's  CNIC :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 210, 93, 17);

        TF_CNIC.setForeground(new java.awt.Color(102, 102, 102));
        TF_CNIC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_CNIC);
        TF_CNIC.setBounds(150, 180, 171, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CNIC :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 180, 40, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DOB :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(360, 180, 35, 17);

        TF_dob.setForeground(new java.awt.Color(102, 102, 102));
        TF_dob.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        TF_dob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_dob);
        TF_dob.setBounds(460, 180, 171, 20);

        TF_fathername.setForeground(new java.awt.Color(102, 102, 102));
        TF_fathername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_fathername);
        TF_fathername.setBounds(150, 210, 171, 20);

        TF_fatherCNIC.setForeground(new java.awt.Color(102, 102, 102));
        TF_fatherCNIC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_fatherCNIC);
        TF_fatherCNIC.setBounds(460, 210, 171, 20);

        TF_religion.setForeground(new java.awt.Color(102, 102, 102));
        TF_religion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_religion);
        TF_religion.setBounds(150, 240, 171, 20);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Religion");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 240, 45, 17);

        TF_contacthome.setForeground(new java.awt.Color(102, 102, 102));
        TF_contacthome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_contacthome);
        TF_contacthome.setBounds(150, 270, 171, 20);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Contact (Home) : ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 270, 102, 17);

        TF_mobile.setForeground(new java.awt.Color(102, 102, 102));
        TF_mobile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_mobile);
        TF_mobile.setBounds(460, 270, 171, 20);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Mobile : ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(360, 270, 49, 17);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Postal Address :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 300, 91, 17);

        TF_postaladress.setForeground(new java.awt.Color(102, 102, 102));
        TF_postaladress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_postaladress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_postaladressActionPerformed(evt);
            }
        });
        getContentPane().add(TF_postaladress);
        TF_postaladress.setBounds(150, 300, 480, 20);

        TF_description.setForeground(new java.awt.Color(102, 102, 102));
        TF_description.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_descriptionActionPerformed(evt);
            }
        });
        getContentPane().add(TF_description);
        TF_description.setBounds(150, 480, 530, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Job Description :");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 485, 96, 17);

        TF_district.setForeground(new java.awt.Color(102, 102, 102));
        TF_district.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_district);
        TF_district.setBounds(460, 240, 171, 20);

        NonTeaching_Update_Button.setText("Update");
        NonTeaching_Update_Button.setToolTipText("This Button Updates the Existing Data");
        NonTeaching_Update_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NonTeaching_Update_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NonTeaching_Update_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NonTeaching_Update_Button);
        NonTeaching_Update_Button.setBounds(770, 490, 72, 25);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("District :");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(360, 240, 49, 17);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel26.setText("Form No :");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel26);
        jLabel26.setBounds(20, 120, 70, 17);

        TF_formno.setForeground(new java.awt.Color(102, 102, 102));
        TF_formno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_formno.setFocusable(false);
        TF_formno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_formnoActionPerformed(evt);
            }
        });
        getContentPane().add(TF_formno);
        TF_formno.setBounds(90, 120, 60, 20);

        panel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(panel1);
        panel1.setBounds(20, 100, 905, 10);

        Add_New_Staff_Button.setText("Add New Staff");
        Add_New_Staff_Button.setToolTipText("Adds New Staff Member");
        Add_New_Staff_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_New_Staff_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Add_New_Staff_Button);
        Add_New_Staff_Button.setBounds(790, 70, 102, 25);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Non Teaching Staff Information");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 0, 900, 70);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Permanent Address :");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(20, 330, 117, 17);

        TF_permanentadress.setForeground(new java.awt.Color(102, 102, 102));
        TF_permanentadress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_permanentadress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_permanentadressActionPerformed(evt);
            }
        });
        getContentPane().add(TF_permanentadress);
        TF_permanentadress.setBounds(150, 330, 480, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Qualification");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 350, 660, 40);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Degree/Program");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(20, 390, 200, 17);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Year Passing");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(250, 390, 80, 17);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Grade / %age");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(370, 390, 80, 17);

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Board/University");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(480, 390, 190, 17);

        TF_degree1.setForeground(new java.awt.Color(102, 102, 102));
        TF_degree1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_degree1);
        TF_degree1.setBounds(20, 420, 200, 20);

        TF_year1.setForeground(new java.awt.Color(102, 102, 102));
        TF_year1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_year1);
        TF_year1.setBounds(250, 420, 80, 20);

        TF_grade1.setForeground(new java.awt.Color(102, 102, 102));
        TF_grade1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_grade1);
        TF_grade1.setBounds(370, 420, 80, 20);

        TF_university1.setForeground(new java.awt.Color(102, 102, 102));
        TF_university1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_university1);
        TF_university1.setBounds(480, 420, 200, 20);

        TF_degree2.setForeground(new java.awt.Color(102, 102, 102));
        TF_degree2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_degree2);
        TF_degree2.setBounds(20, 450, 200, 20);

        TF_year2.setForeground(new java.awt.Color(102, 102, 102));
        TF_year2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_year2);
        TF_year2.setBounds(250, 450, 80, 20);

        TF_grade2.setForeground(new java.awt.Color(102, 102, 102));
        TF_grade2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_grade2);
        TF_grade2.setBounds(370, 450, 80, 20);

        TF_university2.setForeground(new java.awt.Color(102, 102, 102));
        TF_university2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_university2);
        TF_university2.setBounds(480, 450, 200, 20);

        lbl_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_Image);
        lbl_Image.setBounds(770, 150, 140, 160);

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete);
        Delete.setBounds(850, 490, 70, 23);

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(790, 320, 110, 23);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/misc/950, 550 Background.jpg"))); // NOI18N
        getContentPane().add(jLabel33);
        jLabel33.setBounds(0, 0, 950, 550);

        setSize(new java.awt.Dimension(952, 579));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TF_staffidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_staffidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_staffidActionPerformed

    private void TF_postaladressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_postaladressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_postaladressActionPerformed

    private void TF_descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_descriptionActionPerformed

    private void Add_New_Staff_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_New_Staff_ButtonActionPerformed
        dispose();
        New_Non_teaching_form1 obj = new New_Non_teaching_form1();
        obj.timereciever4(month, year);
        obj.setVisible(true);
        Main_Page.jButton9.setEnabled(false);
    }//GEN-LAST:event_Add_New_Staff_ButtonActionPerformed

    private void TF_permanentadressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_permanentadressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_permanentadressActionPerformed

    void getting_data_into_fields() {

        staffid = TF_staffid.getText();
        firstname = TF_firstname.getText();
        lastname = TF_lastname.getText();
        CNIC = TF_CNIC.getText();
        DOB = TF_dob.getText();
        fathername = TF_fathername.getText();
        fatherCNIC = TF_fatherCNIC.getText();
        religion = TF_religion.getText();
        district = TF_district.getText();
        contacthome = TF_contacthome.getText();
        mobile = TF_mobile.getText();
        postaladress = TF_postaladress.getText();
        permanentadress = TF_permanentadress.getText();
        degree1 = TF_degree1.getText();
        year1 = TF_year1.getText();
        grade1 = TF_grade1.getText();
        university1 = TF_university1.getText();
        degree2 = TF_degree2.getText();
        year2 = TF_year2.getText();
        grade2 = TF_grade2.getText();
        university2 = TF_university2.getText();
        description = TF_description.getText();
    }

    void update_data_into_database() {
        /*String non_teaching_staff_query;
        String query_attendance;
         */
       
        pic_adress = pic_adress.replace("\\", "\\\\");
        
        
        String query1 = "UPDATE teacher_admission SET first_name = '" + firstname + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query2 = "UPDATE teacher_admission SET last_name = '" + lastname + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query3 = "UPDATE teacher_admission SET teacher_cnic = '" + CNIC + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query4 = "UPDATE teacher_admission SET dob = '" + DOB + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query5 = "UPDATE teacher_admission SET fathers_name = '" + fathername + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query6 = "UPDATE teacher_admission SET fathers_cnic = '" + fatherCNIC + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query7 = "UPDATE teacher_admission SET religion = '" + religion + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query8 = "UPDATE teacher_admission SET District = '" + district + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query9 = "UPDATE teacher_admission SET contact_home = '" + contacthome + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query10 = "UPDATE teacher_admission SET mobile = '" + mobile + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query12 = "UPDATE teacher_admission SET postal_address = '" + postaladress + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query13 = "UPDATE teacher_admission SET permanent_address = '" + permanentadress + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query14 = "UPDATE teacher_admission SET degree1 = '" + degree1 + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query15 = "UPDATE teacher_admission SET year_passing1 = '" + year1 + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query16 = "UPDATE teacher_admission SET grade1 = '" + grade1 + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query17 = "UPDATE teacher_admission SET uni1 = '" + university1 + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query18 = "UPDATE teacher_admission SET degree2 = '" + degree2 + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query19 = "UPDATE teacher_admission SET year_passing2 = '" + year2 + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query20 = "UPDATE teacher_admission SET grade2 = '" + grade2 + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query21 = "UPDATE teacher_admission SET uni2 = '" + university2 + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        String query22 = "UPDATE teacher_admission SET picadress = '" + pic_adress + "' where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";

        String salaryupdate = "UPDATE salary SET staffname = '" + firstname + "' where staffid = '" + staffid + "' AND stafftype = 'non_teaching';";

        String Query_attendance_change = "UPDATE teacher_attendance_" + month + "_" + year + " SET Name = '" + firstname + "' where Staff_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/misc", "root", "");
            //here sonoo is database name, root is username and password
            java.sql.Statement stmt = con.createStatement();

            stmt.executeUpdate(query1);
            stmt.executeUpdate(query2);
            stmt.executeUpdate(query3);
            stmt.executeUpdate(query4);
            stmt.executeUpdate(query5);
            stmt.executeUpdate(query6);
            stmt.executeUpdate(query7);
            stmt.executeUpdate(query8);
            stmt.executeUpdate(query9);
            stmt.executeUpdate(query10);
            stmt.executeUpdate(query12);
            stmt.executeUpdate(query13);
            stmt.executeUpdate(query14);
            stmt.executeUpdate(query15);
            stmt.executeUpdate(query16);
            stmt.executeUpdate(query17);
            stmt.executeUpdate(query18);
            stmt.executeUpdate(query19);
            stmt.executeUpdate(query20);
            stmt.executeUpdate(query21);
            stmt.executeUpdate(query22);

            stmt.executeUpdate(salaryupdate);

            stmt.executeUpdate(Query_attendance_change);

            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    void Set_field_to_empty() {
        TF_formno.setText("");
        TF_staffid.setText("");
        TF_firstname.setText("");
        TF_lastname.setText("");
        TF_CNIC.setText("");
        TF_dob.setText("");
        TF_fathername.setText("");
        TF_fatherCNIC.setText("");
        TF_religion.setText("");
        TF_district.setText("");
        TF_contacthome.setText("");
        TF_mobile.setText("");
        TF_postaladress.setText("");
        lbl_Image.setIcon(null);
        TF_permanentadress.setText("");
        TF_degree1.setText("");
        TF_year1.setText("");
        TF_grade1.setText("");
        TF_university1.setText("");
        TF_degree2.setText("");
        TF_year2.setText("");
        TF_grade2.setText("");
        TF_university2.setText("");
        TF_description.setText("");
        lbl_Image.setIcon(null);

    }

    private void NonTeaching_Update_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NonTeaching_Update_ButtonActionPerformed

        int select = JOptionPane.showConfirmDialog(null, "Are you sure you want to Update");
        switch (select) {
            case 0:
                getting_data_into_fields();
                update_data_into_database();
                Set_field_to_empty();
                JOptionPane.showMessageDialog(null, "Data Updated Successfully");
                break;

            case 1:
                JOptionPane.showConfirmDialog(null, "The Data is Not Updated");
                break;

            case 2:
                break;

            default:
                JOptionPane.showMessageDialog(null, "Error 404");

        }


    }//GEN-LAST:event_NonTeaching_Update_ButtonActionPerformed

    int Staff_found_or_not(String stafftype1, String staffRollno) {
        int found = 0;

        String Query = "select * from teacher_admission where Staff_type = '" + stafftype1 + "';";

        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/misc", "root", "");

            PreparedStatement stmt = con.prepareStatement(Query);
            ResultSet r1 = stmt.executeQuery();

            while (r1.next()) {
                String rollnogetter = r1.getString("teacher_id");

                if (rollnogetter == null ? staffRollno == null : rollnogetter.equals(staffRollno)) {
                    found = 1;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        return found;
    }

    private void NonTeaching_Search_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NonTeaching_Search_ButtonActionPerformed
        staffid = TF_staffid.getText();

        String stafftype = "non_teaching";

        int foundornot = Staff_found_or_not(stafftype, staffid);

        if (foundornot == 1) {

            if ("".equals(staffid)) {
                JOptionPane.showMessageDialog(null, "Enter the Staff id");
            } else {

                String teacher_search_query;

                teacher_search_query = "select * from teacher_admission where teacher_id = '" + staffid + "' AND Staff_type = '" + stafftype + "';";
                try {

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/misc", "root", "");

                    PreparedStatement stmt = con.prepareStatement(teacher_search_query);
                    ResultSet r1 = stmt.executeQuery();

                    r1.next();

                    formno = r1.getString("formno");
                    firstname = r1.getString("first_name");
                    lastname = r1.getString("last_name");
                    CNIC = r1.getString("teacher_cnic");
                    DOB = r1.getString("dob");
                    fathername = r1.getString("fathers_name");
                    fatherCNIC = r1.getString("fathers_cnic");
                    religion = r1.getString("religion");
                    district = r1.getString("District");
                    contacthome = r1.getString("contact_home");
                    mobile = r1.getString("mobile");
                    postaladress = r1.getString("postal_address");
                    permanentadress = r1.getString("permanent_address");
                    degree1 = r1.getString("degree1");
                    year1 = r1.getString("year_passing1");
                    grade1 = r1.getString("grade1");
                    university1 = r1.getString("uni1");
                    degree2 = r1.getString("degree2");
                    year2 = r1.getString("year_passing2");
                    grade2 = r1.getString("grade2");
                    university2 = r1.getString("uni2");
                    description = r1.getString("job_description");
                    pic_adress = r1.getString("picadress");

                    con.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

                put_values_to_textfields();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Non Teacher (Staff) not Found");
        }

    }//GEN-LAST:event_NonTeaching_Search_ButtonActionPerformed

    private void TF_formnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_formnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_formnoActionPerformed

    private void closingnonteacherform(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closingnonteacherform
        dispose();
        Main_Page.jButton9.setEnabled(true);
    }//GEN-LAST:event_closingnonteacherform

    String imgPath = null;
    String path = null;

    public ImageIcon ResizeImage(String ImagePath, byte[] pic) {
        ImageIcon MyImage = null;
        if (ImagePath != null) {
            MyImage = new ImageIcon(ImagePath);
        } else {
            MyImage = new ImageIcon(pic);
        }
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lbl_Image.getWidth(), lbl_Image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Imges", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        //if the user click on save in JFileChoose
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            path = selectedFile.getAbsolutePath();
            lbl_Image.setIcon(ResizeImage(path, null));
            imgPath = path;
            pic_adress = path;
            path = path.replace("\\", "\\\\");

        } //if the user click on save in Jfilechooser
        else if (result == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "No File Slect");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    void Delete_non_Teaching(){
       String query1 = "DELETE from teacher_admission where teacher_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
       String query2 = "DELETE from teacher_attendance_" + month + "_" + year + " where Staff_id = '" + staffid + "' AND Staff_type = 'non_teaching';";
       String query3 = "DELETE from salary where staffid = '" + staffid + "' AND stafftype = 'non_teaching';";
try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/misc","root","");
            //here sonoo is database name, root is username and password
            java.sql.Statement stmt=con.createStatement();
            
            stmt.executeUpdate(query1);
            stmt.executeUpdate(query3);
            stmt.executeUpdate(query2);
            
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
 
    }
    
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed

        int select = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this data");
        switch (select) {
            case 0:
                Delete_non_Teaching();
                Set_field_to_empty();
                JOptionPane.showMessageDialog(null, "Teacher Deleted Succesfully");
                break;

            case 1:
                JOptionPane.showMessageDialog(null, "The Data is not Deleted");
                break;

            case 2:
                break;

            default:
                JOptionPane.showMessageDialog(null, "Error 404");
        }

    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Non_teaching_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Non_teaching_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Non_teaching_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Non_teaching_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Non_teaching_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_New_Staff_Button;
    private javax.swing.JButton Delete;
    private javax.swing.JButton NonTeaching_Search_Button;
    private javax.swing.JButton NonTeaching_Update_Button;
    private javax.swing.JTextField TF_CNIC;
    private javax.swing.JTextField TF_contacthome;
    private javax.swing.JTextField TF_degree1;
    private javax.swing.JTextField TF_degree2;
    private javax.swing.JTextField TF_description;
    private javax.swing.JTextField TF_district;
    private javax.swing.JFormattedTextField TF_dob;
    private javax.swing.JTextField TF_fatherCNIC;
    private javax.swing.JTextField TF_fathername;
    private javax.swing.JTextField TF_firstname;
    private javax.swing.JTextField TF_formno;
    private javax.swing.JTextField TF_grade1;
    private javax.swing.JTextField TF_grade2;
    private javax.swing.JTextField TF_lastname;
    private javax.swing.JTextField TF_mobile;
    private javax.swing.JTextField TF_permanentadress;
    private javax.swing.JTextField TF_postaladress;
    private javax.swing.JTextField TF_religion;
    private javax.swing.JTextField TF_staffid;
    private javax.swing.JTextField TF_university1;
    private javax.swing.JTextField TF_university2;
    private javax.swing.JTextField TF_year1;
    private javax.swing.JTextField TF_year2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_Image;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
