/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misc;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Abubakar Manzoor
 */
public class Teacher_form extends javax.swing.JFrame {

    /**
     * Creates new form Student_form
     */
    public Teacher_form() {
        initComponents();
    }

    void timereciever(String month1, int year1) {
        month = month1;
        year = year1;
    }

    String month;
    int year;

    String formno;
    String teacherid;
    String firstname;
    String lastname;
    String teacherCNIC;
    String dob;
    String fathername;
    String fatherCNIC;
    String religion;
    String district;
    String contacthome;
    String contactmobile;
    String postaladress;
    String permanentadress;

    String degree1;
    String year1;
    String grade1;
    String university1;
    String degree2;
    String year2;
    String grade2;
    String university2;
    String degree3;
    String year3;
    String grade3;
    String university3;
    String degree4;
    String year4;
    String grade4;
    String university4;
    String degree5;
    String year5;
    String grade5;
    String university5;
    String pic_adress;

    public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TF_teacherid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Teacher_Search_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TF_firstname = new javax.swing.JTextField();
        TF_lastname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TF_CNIC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TF_dob = new javax.swing.JFormattedTextField();
        TF_fathername = new javax.swing.JTextField();
        TF_fatherCNIC = new javax.swing.JTextField();
        TF_religion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TF_contacthome = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TF_contactmobile = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TF_postaladress = new javax.swing.JTextField();
        TF_permanentadress = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TF_district = new javax.swing.JTextField();
        TF_degree1 = new javax.swing.JTextField();
        TF_year1 = new javax.swing.JTextField();
        TF_grade1 = new javax.swing.JTextField();
        TF_university1 = new javax.swing.JTextField();
        Teacher_Update_Button = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        TF_formno = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        Add_New_Teacher_Button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        TF_university2 = new javax.swing.JTextField();
        TF_grade2 = new javax.swing.JTextField();
        TF_year2 = new javax.swing.JTextField();
        TF_degree2 = new javax.swing.JTextField();
        TF_university3 = new javax.swing.JTextField();
        TF_grade3 = new javax.swing.JTextField();
        TF_year3 = new javax.swing.JTextField();
        TF_degree3 = new javax.swing.JTextField();
        TF_university4 = new javax.swing.JTextField();
        TF_grade4 = new javax.swing.JTextField();
        TF_year4 = new javax.swing.JTextField();
        TF_degree4 = new javax.swing.JTextField();
        TF_university5 = new javax.swing.JTextField();
        TF_grade5 = new javax.swing.JTextField();
        TF_year5 = new javax.swing.JTextField();
        TF_degree5 = new javax.swing.JTextField();
        lbl_Image = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Teacher Information");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closingteacherform(evt);
            }
        });
        getContentPane().setLayout(null);

        TF_teacherid.setForeground(new java.awt.Color(102, 102, 102));
        TF_teacherid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_teacherid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_teacheridActionPerformed(evt);
            }
        });
        getContentPane().add(TF_teacherid);
        TF_teacherid.setBounds(100, 50, 60, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Teacher ID :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 50, 80, 17);

        Teacher_Search_Button.setText("Search");
        Teacher_Search_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Teacher_Search_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Teacher_Search_Button);
        Teacher_Search_Button.setBounds(180, 50, 70, 22);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("First Name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 130, 70, 17);

        TF_firstname.setForeground(new java.awt.Color(102, 102, 102));
        TF_firstname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_firstname);
        TF_firstname.setBounds(150, 130, 171, 20);

        TF_lastname.setForeground(new java.awt.Color(102, 102, 102));
        TF_lastname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_lastname);
        TF_lastname.setBounds(460, 130, 171, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Last Name :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 130, 68, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Father's  Name :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 190, 93, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Father's  CNIC :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 190, 93, 17);

        TF_CNIC.setForeground(new java.awt.Color(102, 102, 102));
        TF_CNIC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_CNIC);
        TF_CNIC.setBounds(150, 160, 171, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Teacher's CNIC :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 160, 99, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("DOB :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(360, 160, 35, 17);

        TF_dob.setForeground(new java.awt.Color(102, 102, 102));
        TF_dob.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        TF_dob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_dob);
        TF_dob.setBounds(460, 160, 171, 20);

        TF_fathername.setForeground(new java.awt.Color(102, 102, 102));
        TF_fathername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_fathername);
        TF_fathername.setBounds(150, 190, 171, 20);

        TF_fatherCNIC.setForeground(new java.awt.Color(102, 102, 102));
        TF_fatherCNIC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_fatherCNIC);
        TF_fatherCNIC.setBounds(460, 190, 171, 20);

        TF_religion.setForeground(new java.awt.Color(102, 102, 102));
        TF_religion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_religion);
        TF_religion.setBounds(150, 220, 171, 20);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Religion");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 220, 45, 17);

        TF_contacthome.setForeground(new java.awt.Color(102, 102, 102));
        TF_contacthome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_contacthome);
        TF_contacthome.setBounds(150, 250, 171, 20);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Contact (Home) : ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 250, 102, 17);

        TF_contactmobile.setForeground(new java.awt.Color(102, 102, 102));
        TF_contactmobile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_contactmobile);
        TF_contactmobile.setBounds(460, 250, 171, 20);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Mobile : ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(360, 250, 49, 17);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Postal Address :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 280, 91, 17);

        TF_postaladress.setForeground(new java.awt.Color(102, 102, 102));
        TF_postaladress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_postaladress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_postaladressActionPerformed(evt);
            }
        });
        getContentPane().add(TF_postaladress);
        TF_postaladress.setBounds(150, 280, 480, 20);

        TF_permanentadress.setForeground(new java.awt.Color(102, 102, 102));
        TF_permanentadress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_permanentadress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_permanentadressActionPerformed(evt);
            }
        });
        getContentPane().add(TF_permanentadress);
        TF_permanentadress.setBounds(150, 310, 480, 20);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Permanent Address :");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 310, 117, 17);

        TF_district.setForeground(new java.awt.Color(102, 102, 102));
        TF_district.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_district);
        TF_district.setBounds(460, 220, 171, 20);

        TF_degree1.setForeground(new java.awt.Color(102, 102, 102));
        TF_degree1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_degree1);
        TF_degree1.setBounds(20, 400, 200, 20);

        TF_year1.setForeground(new java.awt.Color(102, 102, 102));
        TF_year1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_year1);
        TF_year1.setBounds(250, 400, 80, 20);

        TF_grade1.setForeground(new java.awt.Color(102, 102, 102));
        TF_grade1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_grade1);
        TF_grade1.setBounds(370, 400, 80, 20);

        TF_university1.setForeground(new java.awt.Color(102, 102, 102));
        TF_university1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_university1);
        TF_university1.setBounds(479, 400, 190, 20);

        Teacher_Update_Button.setText("Update");
        Teacher_Update_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Teacher_Update_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Teacher_Update_Button);
        Teacher_Update_Button.setBounds(760, 500, 72, 25);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setText("District :");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(360, 220, 49, 17);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel26.setText("Form No :");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(20, 100, 59, 17);

        TF_formno.setForeground(new java.awt.Color(102, 102, 102));
        TF_formno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_formno);
        TF_formno.setBounds(100, 100, 60, 20);

        panel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(panel1);
        panel1.setBounds(20, 80, 905, 10);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Qualification");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 330, 650, 40);

        Add_New_Teacher_Button.setText("Add New Teacher");
        Add_New_Teacher_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_New_Teacher_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Add_New_Teacher_Button);
        Add_New_Teacher_Button.setBounds(780, 50, 120, 25);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Teacher Information");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 10, 900, 40);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Degree/Program");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(20, 370, 200, 17);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Year Passing");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(250, 370, 80, 17);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Grade / %age");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(370, 370, 80, 17);

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Board/University");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(480, 370, 190, 17);

        TF_university2.setForeground(new java.awt.Color(102, 102, 102));
        TF_university2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_university2);
        TF_university2.setBounds(479, 430, 190, 20);

        TF_grade2.setForeground(new java.awt.Color(102, 102, 102));
        TF_grade2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_grade2);
        TF_grade2.setBounds(370, 430, 80, 20);

        TF_year2.setForeground(new java.awt.Color(102, 102, 102));
        TF_year2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_year2);
        TF_year2.setBounds(250, 430, 80, 20);

        TF_degree2.setForeground(new java.awt.Color(102, 102, 102));
        TF_degree2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_degree2);
        TF_degree2.setBounds(20, 430, 200, 20);

        TF_university3.setForeground(new java.awt.Color(102, 102, 102));
        TF_university3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_university3);
        TF_university3.setBounds(479, 460, 190, 20);

        TF_grade3.setForeground(new java.awt.Color(102, 102, 102));
        TF_grade3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_grade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_grade3ActionPerformed(evt);
            }
        });
        getContentPane().add(TF_grade3);
        TF_grade3.setBounds(370, 460, 80, 20);

        TF_year3.setForeground(new java.awt.Color(102, 102, 102));
        TF_year3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_year3);
        TF_year3.setBounds(250, 460, 80, 20);

        TF_degree3.setForeground(new java.awt.Color(102, 102, 102));
        TF_degree3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_degree3);
        TF_degree3.setBounds(20, 460, 200, 20);

        TF_university4.setForeground(new java.awt.Color(102, 102, 102));
        TF_university4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_university4);
        TF_university4.setBounds(479, 490, 190, 20);

        TF_grade4.setForeground(new java.awt.Color(102, 102, 102));
        TF_grade4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_grade4);
        TF_grade4.setBounds(370, 490, 80, 20);

        TF_year4.setForeground(new java.awt.Color(102, 102, 102));
        TF_year4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_year4);
        TF_year4.setBounds(250, 490, 80, 20);

        TF_degree4.setForeground(new java.awt.Color(102, 102, 102));
        TF_degree4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_degree4);
        TF_degree4.setBounds(20, 490, 200, 20);

        TF_university5.setForeground(new java.awt.Color(102, 102, 102));
        TF_university5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_university5);
        TF_university5.setBounds(479, 520, 190, 20);

        TF_grade5.setForeground(new java.awt.Color(102, 102, 102));
        TF_grade5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_grade5);
        TF_grade5.setBounds(370, 520, 80, 20);

        TF_year5.setForeground(new java.awt.Color(102, 102, 102));
        TF_year5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_year5);
        TF_year5.setBounds(250, 520, 80, 20);

        TF_degree5.setForeground(new java.awt.Color(102, 102, 102));
        TF_degree5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TF_degree5);
        TF_degree5.setBounds(20, 520, 200, 20);

        lbl_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_Image);
        lbl_Image.setBounds(770, 130, 140, 160);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(840, 500, 63, 23);

        jButton2.setText("Browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(783, 300, 120, 23);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/misc/950, 550 Background.jpg"))); // NOI18N
        getContentPane().add(jLabel33);
        jLabel33.setBounds(0, 0, 950, 550);

        setSize(new java.awt.Dimension(955, 579));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TF_teacheridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_teacheridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_teacheridActionPerformed

    private void TF_postaladressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_postaladressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_postaladressActionPerformed

    private void TF_permanentadressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_permanentadressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_permanentadressActionPerformed

    private void TF_grade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_grade3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_grade3ActionPerformed

    private void Add_New_Teacher_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_New_Teacher_ButtonActionPerformed
        dispose();
        new_Teacher_form obj = new new_Teacher_form();
        obj.timereciever2(month, year);
        obj.setVisible(true);
        Main_Page.jButton6.setEnabled(false);
    }//GEN-LAST:event_Add_New_Teacher_ButtonActionPerformed

    void put_values_to_textfields() {
        TF_formno.setText(formno);
        TF_firstname.setText(firstname);
        TF_lastname.setText(lastname);
        TF_CNIC.setText(teacherCNIC);
        TF_dob.setText(dob);
        TF_fathername.setText(fathername);
        TF_fatherCNIC.setText(fatherCNIC);
        TF_religion.setText(religion);
        TF_district.setText(district);
        TF_contacthome.setText(contacthome);
        TF_contactmobile.setText(contactmobile);
        TF_postaladress.setText(postaladress);
        TF_permanentadress.setText(permanentadress);
        TF_degree1.setText(degree1);
        TF_year1.setText(year1);
        TF_grade1.setText(grade1);
        TF_university1.setText(university1);
        TF_degree2.setText(degree2);
        TF_year2.setText(year2);
        TF_grade2.setText(grade2);
        TF_university2.setText(university2);
        TF_degree3.setText(degree3);
        TF_year3.setText(year3);
        TF_grade3.setText(grade3);
        TF_university3.setText(university3);
        TF_degree4.setText(degree4);
        TF_year4.setText(year4);
        TF_grade4.setText(grade4);
        TF_university4.setText(university4);
        TF_degree5.setText(degree5);
        TF_year5.setText(year5);
        TF_grade5.setText(grade5);
        TF_university5.setText(university5);
        lbl_Image.setIcon(ResizeImage(pic_adress, null));

    }

    //this function set all fields to empty
    public void Set_field_to_empty() {
        TF_formno.setText("");
        TF_teacherid.setText("");
        TF_firstname.setText("");
        TF_lastname.setText("");
        TF_CNIC.setText("");
        TF_dob.setText("");
        TF_fathername.setText("");
        TF_fatherCNIC.setText("");
        TF_religion.setText("");
        TF_district.setText("");
        TF_contacthome.setText("");
        TF_contactmobile.setText("");
        TF_postaladress.setText("");
        TF_permanentadress.setText("");
        TF_degree1.setText("");
        TF_year1.setText("");
        TF_grade1.setText("");
        TF_university1.setText("");
        TF_degree2.setText("");
        TF_year2.setText("");
        TF_grade2.setText("");
        TF_university2.setText("");
        TF_degree3.setText("");
        TF_year3.setText("");
        TF_grade3.setText("");
        TF_university3.setText("");
        TF_degree4.setText("");
        TF_year4.setText("");
        TF_grade4.setText("");
        TF_university4.setText("");
        TF_degree5.setText("");
        TF_year5.setText("");
        TF_grade5.setText("");
        TF_university5.setText("");
        lbl_Image.setIcon(null);

    }

    int teacher_found_or_not(String stafftype1, String staffRollno) {
        int found = 0;

        String Query = "select * from teacher_admission where Staff_type = '" + stafftype1 + "';";

        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/misc", "root", "");

            PreparedStatement stmt = con.prepareStatement(Query);
            ResultSet r1 = stmt.executeQuery();

            while (r1.next()) {
                String rollnogetter = r1.getString("teacher_id");

                if (rollnogetter == null ? staffRollno == null : rollnogetter.equals(staffRollno)) {
                    found = 1;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        return found;
    }


    private void Teacher_Search_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Teacher_Search_ButtonActionPerformed

        teacherid = TF_teacherid.getText();
        String stafftype = "teacher";

        if ("".equals(teacherid)) {
            JOptionPane.showMessageDialog(null, "Enter the Roll No");
        } else {

            int foundornot = teacher_found_or_not(stafftype, teacherid);

            if (foundornot == 1) {

                String query_search_teacher = "select * from teacher_admission where teacher_id = '" + teacherid + "' AND Staff_type = '" + stafftype + "';";
                try {

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/misc", "root", "");

                    PreparedStatement stmt = con.prepareStatement(query_search_teacher);
                    ResultSet r1 = stmt.executeQuery();

                    r1.next();

                    formno = r1.getString("formno");
                    firstname = r1.getString("first_name");
                    lastname = r1.getString("last_name");
                    teacherCNIC = r1.getString("teacher_cnic");
                    dob = r1.getString("dob");
                    fathername = r1.getString("fathers_name");
                    fatherCNIC = r1.getString("fathers_cnic");
                    religion = r1.getString("religion");
                    district = r1.getString("District");
                    contacthome = r1.getString("contact_home");
                    contactmobile = r1.getString("mobile");
                    postaladress = r1.getString("postal_address");
                    permanentadress = r1.getString("permanent_address");
                    degree1 = r1.getString("degree1");
                    year1 = r1.getString("year_passing1");
                    grade1 = r1.getString("grade1");
                    university1 = r1.getString("uni1");
                    degree2 = r1.getString("degree2");
                    year2 = r1.getString("year_passing2");
                    grade2 = r1.getString("grade2");
                    university2 = r1.getString("uni2");
                    degree3 = r1.getString("degree3");
                    year3 = r1.getString("year_passing3");
                    grade3 = r1.getString("grade3");
                    university3 = r1.getString("uni3");
                    degree4 = r1.getString("degree4");
                    year4 = r1.getString("year_passing4");
                    grade4 = r1.getString("grade4");
                    university4 = r1.getString("uni4");
                    degree5 = r1.getString("degree5");
                    year5 = r1.getString("year_passing5");
                    grade5 = r1.getString("grade5");
                    university5 = r1.getString("uni5");
                    pic_adress = r1.getString("picadress");

                    con.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

                put_values_to_textfields();
            } else {
                Set_field_to_empty();
                JOptionPane.showMessageDialog(null, "Teacher Not Found");
            }
        }
    }//GEN-LAST:event_Teacher_Search_ButtonActionPerformed

    void get_data_from_database() {
        teacherid = TF_teacherid.getText();
        firstname = TF_firstname.getText();
        lastname = TF_lastname.getText();
        teacherCNIC = TF_CNIC.getText();
        dob = TF_dob.getText();
        fathername = TF_fathername.getText();
        fatherCNIC = TF_fatherCNIC.getText();
        religion = TF_religion.getText();
        district = TF_district.getText();
        contacthome = TF_contacthome.getText();
        contactmobile = TF_contactmobile.getText();
        postaladress = TF_postaladress.getText();
        permanentadress = TF_permanentadress.getText();
        degree1 = TF_degree1.getText();
        year1 = TF_year1.getText();
        grade1 = TF_grade1.getText();
        university1 = TF_university1.getText();
        degree2 = TF_degree2.getText();
        year2 = TF_year2.getText();
        grade2 = TF_grade2.getText();
        university2 = TF_university2.getText();
        degree3 = TF_degree3.getText();
        year3 = TF_year3.getText();
        grade3 = TF_grade3.getText();
        university3 = TF_university3.getText();
        degree4 = TF_degree4.getText();
        year4 = TF_year4.getText();
        grade4 = TF_grade4.getText();
        university4 = TF_university4.getText();
        degree5 = TF_degree5.getText();
        year5 = TF_year5.getText();
        grade5 = TF_grade5.getText();
        university5 = TF_university5.getText();
    }

    void data_update_into_database() {

        pic_adress = pic_adress.replace("\\", "\\\\");

        
        String query1 = "UPDATE teacher_admission SET first_name = '" + firstname + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query2 = "UPDATE teacher_admission SET last_name = '" + lastname + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query3 = "UPDATE teacher_admission SET teacher_cnic = '" + teacherCNIC + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query4 = "UPDATE teacher_admission SET dob = '" + dob + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query5 = "UPDATE teacher_admission SET fathers_name = '" + fathername + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query6 = "UPDATE teacher_admission SET fathers_cnic = '" + fatherCNIC + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query7 = "UPDATE teacher_admission SET religion = '" + religion + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query8 = "UPDATE teacher_admission SET District = '" + district + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query9 = "UPDATE teacher_admission SET contact_home = '" + contacthome + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query10 = "UPDATE teacher_admission SET mobile = '" + contactmobile + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query12 = "UPDATE teacher_admission SET postal_address = '" + postaladress + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query13 = "UPDATE teacher_admission SET permanent_address = '" + permanentadress + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query14 = "UPDATE teacher_admission SET degree1 = '" + degree1 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query15 = "UPDATE teacher_admission SET year_passing1 = '" + year1 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query16 = "UPDATE teacher_admission SET grade1 = '" + grade1 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query17 = "UPDATE teacher_admission SET uni1 = '" + university1 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query18 = "UPDATE teacher_admission SET degree2 = '" + degree2 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query19 = "UPDATE teacher_admission SET year_passing2 = '" + year2 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query20 = "UPDATE teacher_admission SET grade2 = '" + grade2 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher'";
        String query21 = "UPDATE teacher_admission SET uni2 = '" + university2 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query22 = "UPDATE teacher_admission SET degree3 = '" + degree3 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query23 = "UPDATE teacher_admission SET year_passing3 = '" + year3 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query24 = "UPDATE teacher_admission SET grade3 = '" + grade3 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query25 = "UPDATE teacher_admission SET uni3 = '" + university3 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query26 = "UPDATE teacher_admission SET degree4 = '" + degree4 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query27 = "UPDATE teacher_admission SET year_passing4 = '" + year4 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query28 = "UPDATE teacher_admission SET grade4 = '" + grade4 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query29 = "UPDATE teacher_admission SET uni4 = '" + university4 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query30 = "UPDATE teacher_admission SET degree5 = '" + degree5 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query31 = "UPDATE teacher_admission SET year_passing5 = '" + year5 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query32 = "UPDATE teacher_admission SET grade5 = '" + grade5 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query33 = "UPDATE teacher_admission SET uni5 = '" + university5 + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query34 = "UPDATE teacher_admission SET picadress = '" + pic_adress + "' where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String Query_attendance_change = "UPDATE teacher_attendance_" + month + "_" + year + " SET Name = '" + firstname + "' where Staff_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String Query_salary_name = "UPDATE salary SET staffname = '" + firstname + "' where staffid = '" + teacherid + "' AND stafftype = 'teacher';";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/misc", "root", "");
            //here sonoo is database name, root is username and password
            java.sql.Statement stmt = con.createStatement();

            stmt.executeUpdate(query1);
            stmt.executeUpdate(query2);
            stmt.executeUpdate(query3);
            stmt.executeUpdate(query4);
            stmt.executeUpdate(query5);
            stmt.executeUpdate(query6);
            stmt.executeUpdate(query7);
            stmt.executeUpdate(query8);
            stmt.executeUpdate(query9);
            stmt.executeUpdate(query10);
            stmt.executeUpdate(query12);
            stmt.executeUpdate(query13);
            stmt.executeUpdate(query14);
            stmt.executeUpdate(query15);
            stmt.executeUpdate(query16);
            stmt.executeUpdate(query17);
            stmt.executeUpdate(query18);
            stmt.executeUpdate(query19);
            stmt.executeUpdate(query20);
            stmt.executeUpdate(query21);
            stmt.executeUpdate(query22);
            stmt.executeUpdate(query23);
            stmt.executeUpdate(query24);
            stmt.executeUpdate(query25);
            stmt.executeUpdate(query26);
            stmt.executeUpdate(query27);
            stmt.executeUpdate(query28);
            stmt.executeUpdate(query29);
            stmt.executeUpdate(query30);
            stmt.executeUpdate(query31);
            stmt.executeUpdate(query32);
            stmt.executeUpdate(query33);
            stmt.executeUpdate(query34);
            stmt.executeUpdate(Query_salary_name);
            stmt.executeUpdate(Query_attendance_change);

            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }


    private void Teacher_Update_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Teacher_Update_ButtonActionPerformed

        int choose = JOptionPane.showConfirmDialog(null, "Are you sure you want to Update this Teacher's Data");

        switch (choose) {
            case 0:
                get_data_from_database();
                data_update_into_database();
                Set_field_to_empty();
                JOptionPane.showMessageDialog(null, "The Data of Teacher is Updated");
                break;

            case 1:
                JOptionPane.showMessageDialog(null, "The Data is not Updated");
                break;

            case 2:
                break;

            default:
                JOptionPane.showMessageDialog(null, "Error 404");
        }

    }//GEN-LAST:event_Teacher_Update_ButtonActionPerformed

    private void closingteacherform(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closingteacherform
        dispose();
        Main_Page.jButton6.setEnabled(true);
    }//GEN-LAST:event_closingteacherform

    void Teacher_deletion() {

        String query1 = "DELETE from teacher_admission where teacher_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query2 = "DELETE from teacher_attendance_" + month + "_" + year + " where Staff_id = '" + teacherid + "' AND Staff_type = 'teacher';";
        String query3 = "DELETE from salary where staffid = '" + teacherid + "' AND Staff_type = 'teacher';";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/misc", "root", "");
            //here sonoo is database name, root is username and password
            java.sql.Statement stmt = con.createStatement();

            stmt.executeUpdate(query1);
            stmt.executeUpdate(query3);
            stmt.executeUpdate(query2);

            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int choose = JOptionPane.showConfirmDialog(null, "Are you sure you want to Delete this Teacher's Data");

        switch (choose) {
            case 0:
                Teacher_deletion();
                Set_field_to_empty();
                JOptionPane.showMessageDialog(null, "The Data of Teacher is Deleted");
                break;

            case 1:
                JOptionPane.showMessageDialog(null, "The Data is not Deleted");
                break;

            case 2:
                break;

            default:
                JOptionPane.showMessageDialog(null, "Error 404");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    String imgPath1 = null;
    String path1 = null;

    //this is the fucntion that resize the image 
    public ImageIcon ResizeImage(String ImagePath, byte[] pic) {
        ImageIcon MyImage = null;
        if (ImagePath != null) {
            MyImage = new ImageIcon(ImagePath);
        } else {
            MyImage = new ImageIcon(pic);
        }
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lbl_Image.getWidth(), lbl_Image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);

        return image;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Imges", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);

        int result = file.showSaveDialog(null);
        //if the user click on save in JFileChoose
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();

            path1 = selectedFile.getAbsolutePath();
            lbl_Image.setIcon(ResizeImage(path1, null));
            imgPath1 = path1;
            
            pic_adress = path1;

            path1 = path1.replace("\\", "\\\\");

        } //if the user click on save in Jfilechooser
        else if (result == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "No File Selected");
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_New_Teacher_Button;
    private javax.swing.JTextField TF_CNIC;
    private javax.swing.JTextField TF_contacthome;
    private javax.swing.JTextField TF_contactmobile;
    private javax.swing.JTextField TF_degree1;
    private javax.swing.JTextField TF_degree2;
    private javax.swing.JTextField TF_degree3;
    private javax.swing.JTextField TF_degree4;
    private javax.swing.JTextField TF_degree5;
    private javax.swing.JTextField TF_district;
    private javax.swing.JFormattedTextField TF_dob;
    private javax.swing.JTextField TF_fatherCNIC;
    private javax.swing.JTextField TF_fathername;
    private javax.swing.JTextField TF_firstname;
    private javax.swing.JTextField TF_formno;
    private javax.swing.JTextField TF_grade1;
    private javax.swing.JTextField TF_grade2;
    private javax.swing.JTextField TF_grade3;
    private javax.swing.JTextField TF_grade4;
    private javax.swing.JTextField TF_grade5;
    private javax.swing.JTextField TF_lastname;
    private javax.swing.JTextField TF_permanentadress;
    private javax.swing.JTextField TF_postaladress;
    private javax.swing.JTextField TF_religion;
    private javax.swing.JTextField TF_teacherid;
    private javax.swing.JTextField TF_university1;
    private javax.swing.JTextField TF_university2;
    private javax.swing.JTextField TF_university3;
    private javax.swing.JTextField TF_university4;
    private javax.swing.JTextField TF_university5;
    private javax.swing.JTextField TF_year1;
    private javax.swing.JTextField TF_year2;
    private javax.swing.JTextField TF_year3;
    private javax.swing.JTextField TF_year4;
    private javax.swing.JTextField TF_year5;
    private javax.swing.JButton Teacher_Search_Button;
    private javax.swing.JButton Teacher_Update_Button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_Image;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
